### ISSUE TITLE
Assert related through anonymous Relationships

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#107]
Change http://linked.art/model/object/aboutness/index.html#related-objects

to instead use a Relationship node that can have at least a label.

**Comment by Conal-Tuohy** [comment]
Can I suggest if we are going beyond a mere `dc:related` to introduce a mediating entity to represent the relationship, that there is an alternative that is ontologically isomorphic, but which is pure CRM?

This would be to replace the "Relationship" node with an instance of CRM `E89 Propositional Object` (which represents the _list of related items_ in the source data). This propositional object, then, `P129 is about` the entity in question, and `P67 refers to` each of the related entities. The object could also have a title of "Related" or some such.

**Comment by azaroth42** [comment]
The directionality of relationships is important (I am my father's child, but not vice versa), and as P129 is a subPropertyOf P67, we can't infer the direction from just those two.

**Comment by Conal-Tuohy** [comment]
The example listed above says

> A  list of related objects is often known for any given object, however the reason for the relation is not recorded

... which is a different case altogether from cases where the nature of the relationship actually _is_ known (i.e. "is parent of"). The case of parenthood can be modelled quite straightforwardly using `E67_Birth` (related to the people concerned with `P97_from_father` and `P98_brought_into-life`) instead of this proposed generic "Relationship" object.

**Comment by workergnome** [comment]
OK--so CRM allows us to express exactly one relationship natively:  biological parenthood.  Adopted siblings need not apply, nor should people whose parents are married to others of the same sex. 

For a non-sibling example: I am my uncle's nephew, but not vice-versa.  Yes, I could model that in CRM  by modeling my entire family tree, add adding semantics for marriage...but that's not a practical way to do it.

And I am my teacher's student, but not vice-versa, which is un-modellable in CRM.

We did discuss doing as you said--by pretending that `is about` and `refers to` are different classes of things, but between the inheritance between them and the fact that that's not at all what the scope notes for those things mean (since many propositional objects refer to things that are not a list of aggregated resources) we felt a separate class that combines the semantics of conceptual items and a different set of semantics that describe aggregations of items was a better solution.

**Comment by workergnome** [comment]
I think there's a confusion here--the documentation describes the semantically weak connection, where we have no information about the role.  There is a proposal (mostly contained in this issue) to add a reification via a `la:Relationship` and a couple (yet undefined) predicates that will allow us to type and and directionality to relationships.  Probably, much like you're suggesting, by extending an existing CRM class (either Propositional or Conceptual Object, likely?) and adding a predicate or two that expresses relationship directionality semantics, and using a (yet unidentified hierarchy) to capture the relationship types.

We do have this data--http://vocab.getty.edu/doc/assoc-rels-matrix.pdf has a bunch of relationships that exist in ULAN, but we haven't been able to model them yet.  (Currently, we create a sub-property of `dc:related` for each relationship, but that's not a tractable solution long-term).

I also personally have this data in my museum provenance records, where family relationships between owners are recorded.  http://www.museumprovenance.org/reference/standard/#party-clauses has my little list of types, but I don't know how to describe them in Linked Art.

I also (not immediately, but potentially) would like to model the interpersonal relationships in another project I've worked on, Six Degrees of Francis Bacon: http://www.sixdegreesoffrancisbacon.com/?ids=10011681,10009062&min_confidence=60&type=network where every edge has a directed relationship from their relationship vocabulary.

In all of these cases, we have two people, a directional relationship between them, and a type of that relationship.  IN the 6 Degree case, we also have a time period in which that relationship was valid.

Our hope is that we can find a single pattern that can be used to describe inter-personal relationships of all sorts, which is why we would prefer to use an untyped `la:Relationship` over a `dc:related` to express the simple case, because it's semantically similar enough and makes computability easy.  The two edge cases in the CRM are birth, which is explicitly biological and could coexist with this, and Group Membership, which is useful because groups of people within the CRM also have agency and can operate as a unit.

I _do_ recognize that the CRM has worked to fit every possible human relationship into the bucket of "Group", which stretches the concept and scope note into unrecognizability.  I think they are wary (as you are) of opening the Pandora's box of human-human relationships...but we are looking for a path forward that requires as little work as possible to get off the ground, but still expresses the data that we have.  

I think this is a good venue for these discussions, as is slack, and we appreciate your input on it!

**Comment by azaroth42** [comment]
And not just inter-personal, but arbitrary relationships in general that aren't sufficiently general to be put into an ontology like CRM.  The PDF referenced above has all the relationships from all three published vocabularies. 

I'm sure that there is a good and complex model for "court artist of" involving activities, groups and roles, but it still needs the concept of court-artist-ness. I'm less convinced there's a way to model something like culture A "has parallels with" culture B at all in CRM.

**Comment by Conal-Tuohy** [comment]
In a way it seems that the point of this class is to serve as a semantically weak generalization of a large number of ontologically distinct relationships, but I'm still not clear on the rationale for that: is it all about presentational requirements, i.e. to provide an underpinning for a consistent API that works the same way across a bunch of very different relationships, or to improve tractability of querying? Or is it also to be able to have a way to _model_ statements which themselves are ontologically weak (such as "is related to")? Is it as a way to avoid doing the mapping work? I can understand if that's the case, though I'm less convinced that there _isn't_ a way to model each and every one of those relationships in CRM.

For instance, I don't know what the linked PDF meant by the "parallels" between the cultures; presumably they cultures could be modeled as crm Groups sharing an anonymous Type. i.e. if the parallels were in their method of subsistance, for instance, the shared type would represent "agriculture" or "hunter-gathering" or whatever. By being anonymous and unlabeled, the type simply implies that the cultures share some characteristic.

**Comment by azaroth42** [comment]
Noting that this was discussed on the recent call, and prioritized for work towards a simple pattern for demonstrating relationships that aren't directly in scope, but still valuable to somehow model/describe.

**Comment by azaroth42** [comment]
The way I think about this issue is that there are infinitely many possible relationships, in the same way that there are infinitely many possible classes of object.  For the class extension, we have a strong pattern with `classified_as` to a `Type` from a controlled vocabulary such as AAT.  For example a HumanMadeObject is more specifically a Painting.

We do not have a good cognate extension mechanism for relationships between resources, such as the many social and familial relationships between people.  As RDF and thus Linked Data does not allow for properties on properties (and thus issue #55) so instead we need to reify the property into a resource.  Many of the event related qualifications can be handled with partitioning (such as multiple artists with different roles) however we can't partition physical things to model relationships.

To avoid having to model several anonymous intermediate resources between the related resources, instead we can introduce an 'if necessary' shortcut class called "Relationship".  The relationship has a classification to a Type, which is (in essence) the property in the same way as AttributeAssignment has a classification for the type of relationship. It would have a `from` property and a `to` property, being the subject and object of the relationship respectively. The directionality is important -- A is the student of B, not vice versa.

Thus instead of modeling the activity of knowledge transfer in a formal setting between teachers and students, instead we have a "student of" Type that is added to a Relationship class. These would be deprecated one by one over time as the use of more formal models emerge.

```
{
  "type": "Relationship",
  "classified_as": {"id": "http://vocab.getty.edu/rels/1102", "type": "Type", "_label": "student of"},
  "_label": "student was student of teacher",
  "from": "ulan:student-person",
  "to": "ulan:teacher-person"
}
```

We might then also attach a TimeSpan or Place to the node to qualify the temporal or spatial extent of the relationship.  (To be discussed!)

**Comment by pjhayes** [comment]
Why do you say that "RDF and thus Linked Data does not allow for properties on properties" ? The RDF (and RDFS) syntax and semantics allows for properties to have properties, and for properties to be in classes, etc.. It is entirely agnostic on such 'higher-order' matters. OWL2-DL imposes restrictions on constructions like this, but not RDF itself.

**Comment by azaroth42** [comment]
You can have relationships on the definition of a predicate, but the instance of the predicate cannot be the subject of a triple, as the URI for the predicate is global.  Thus all the recent discussion about property graphs :)

**Comment by marilenadaquino** [comment]
As mentioned during the last call, the [pro ontology](http://purl.org/spar/pro) allows to represent roles in time-related contexts, i.e. roles hold by agents (`foaf:Agent`, which is pretty broad) with respect to other agents. Hence people, organizations and objects can be related to each other by using the same pattern. It’s worth to notice that the only value constrain on the main class `pro:RoleInTime` is that an entity A must have a role in the context of an entity B, while the time span of the role itself is not mandatory. Plus, the class `pro:Role` can be extended by creating/reusing external vocabularies.

According to pro, in the “student/supervisor” example we have two distinct roles, namely: (1) the supervisor’s role and (2) the student’s role. The same pattern can be used for describing n-n relationships (e.g. being supervisor of three students at the same time, and being supervisor of other students at a different time).

In JSON the example “student was student of teacher” mentioned by @azaroth42 would look like:

```
{
  "type": “RoleInTime”,
  “withRole”: {"id": "http://purl.org/spar/scoro/master-student", "type": “Role”, "_label": “master student"},
  "_label": "student A was student of teacher B",
  "isHeldBy": ":student-person",
  "relatesTo": ":supervisor-person”,
  “atTime”: {
	id": "http://whatever.org/student-enrollment-time",  
	"type": "TimeSpan",
	"begin_of_the_begin": "2008-04-01", 
	"end_of_the_end": "2008-09-30"
	}
}
```


For the sake of completeness, the complete example in turtle syntax:

```
@prefix : <http://whatever.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix pro: <http://purl.org/spar/pro/> .
@prefix scoro: <http://purl.org/spar/scoro/> .
@prefix ti: <http://www.ontologydesignpatterns.org/cp/owl/timeinterval.owl#> .
@prefix tvc: <http://www.essepuntato.it/2012/04/tvc/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:student-person a foaf:Person ;
	pro:holdsRoleInTime :student-role-in-time .

:supervisor-person a foaf:Person ;
	pro:holdsRoleInTime :supervisor-role-in-time .

:student-role-in-time a pro:RoleInTime ;
	pro:isHeldBy :student-person ;
	pro:withRole scoro:master-student ;
	pro:relatesToPerson :supervisor-person ;
	tvc:atTime :student-enrollment-time ;
	pro:isPersonContextFor :supervisor-role-in-time .

:supervisor-role-in-time a pro:RoleInTime ;
	pro:isHeldBy :supervisor-person ;
	pro:withRole scoro:supervisor ;
	pro:relatesToPerson :student-person ;
	tvc:atTime :supervisor-teaching-time ;
	pro:isPersonContextFor :student-role-in-time .

:student-enrollment-time a ti:TimeInterval ;
	ti:hasIntervalStartDate "2008-04-01T00:00:00Z"^^xsd:dateTime ;
	ti:hasIntervalEndDate "2008-09-30T23:59:59Z"^^xsd:dateTime .

:supervisor-teaching-time a ti:TimeInterval ;
	ti:hasIntervalStartDate "2000-01-01T00:00:00Z"^^xsd:dateTime .
```

**Comment by pjhayes** [comment]
I may be misunderstanding your usage of ‘predicate’ and ‘relationship’, but if you mean relations, known in RDF-speak as ‘properties’ – things which hold between entities, like is-student-of or has-color – then these can be asserted to hold between relations in RDF. RDF in fact makes no principled distinction between individuals, classes and relationships (properties), so that one can even assert a property of itself, as in the RDFS axiom 

rdfs:range rdfs:range rdfs:Class .

Basically, the RDF semantic model is that names denote entities, and any entity can play any role – that is, it can be an instance (AKA an individual), a class or a property, or any combination of these, as required. 

You say that an instance of a predicate cannot be a triple subject. I am not sure what you mean by this. Relations do not have instances in the sense that classes do. (If they did, an instance would be an ordered pair of individuals, as indeed it is in a formal Tarskian semantics.) But anything that can be identified by an IRI – which is to say, anything – can be the subject of an RDF triple assertion. Your observation of the global nature of an IRI is irrelevant: the scope of an identifier has no bearing on what it can be said to identify, nor vice versa. 

Sorry if I get a bit insistent on these points, but we took a lot of care, and a some original research work, to make the RDF semantic model as liberal and unconstrained as logically possible, and it is slightly grating to read that something "cannot be said" in RDF because of some imagined limitation which is not really present. 

Pat

**Comment by ajs6f** [comment]
If I understand the disagreement correctly, suppose we have:
```
:thing :property :value1
:thing :property :value2
``` 
then we add something like
```
:property :hasQualification :qual
```
we are saying that the qualification holds for both uses of `:property` in the predicate position. This would be why you are saying that "RDF (and RDFS) syntax and semantics allows for properties to have properties". But if we would like to be able to make a qualification on one use of `:property` in the predicate position and not the other, things become much more complex for RDF (not for the property graph model). That is why @azaroth42 is saying "RDF and thus Linked Data does not allow for properties on properties".

I'm not sure if that helps clarify, but I'm starting out hopefully.

**Comment by azaroth42** [comment]
What Adam said :)

Or ...

I'm referring to issue 1 [here](https://www.w3.org/TR/swbp-n-aryRelations/).

Referred to from RDF 1.1 concepts, which states:

> The predicate itself is an IRI and denotes a property, that is, a resource that can be thought of as a binary relation.

Properties are binary relations between individuals, and thus the IRI of the property _as used_ in the predicate position of a particular triple cannot be the subject of another triple. Thus we turn to reification, which is what both Marilena and I propose above.

Or ... if you prefer the ABox / TBox distinction, properties are only individuals in the TBox layer.

Or ... if you prefer the philosophy version, properties in RDF are True Universals and do not have Particulars.

**Comment by Conal-Tuohy** [comment]
Reading @azaroth42's comment about "turning to reification" in an email notification I thought for a horrible moment he and @marilenadaquino were proposing the use of [RDF reification](https://www.w3.org/TR/2014/REC-rdf11-mt-20140225/Overview.html#reification) in Linked Art, and I had to come here to check, but _phew!_ of course they were not ;-)

**Comment by pjhayes** [comment]
> On May 8, 2019, at 10:48 PM, Rob Sanderson <notifications@github.com> wrote:
> 
> What Adam said :)
> 
> Or ...
> 
> I'm referring to issue 1 here <https://www.w3.org/TR/swbp-n-aryRelations/>.
> 
> Referred to from RDF 1.1 concepts, which states:
> 
> The predicate itself is an IRI and denotes a property, that is, a resource that can be thought of as a binary relation.
> 
> Properties are binary relations between individuals,
> 
Yes, though bear in mind that in the RDF semantics, /anything/ can be treated as a relation/property. In technical terminology, RDF has an intensional rather than extensional view of relations, c.f. the above “which /can be thought of/ as…” (my emphasis.) For a precise statement, see https://www.w3.org/TR/rdf11-mt/#simple-interpretations, especially the second ‘technical note’ in that section. And so...
> and thus the IRI of the property as used in the predicate position of a particular triple cannot be the subject of another triple.
> 
… is incorrect. An IRI – the very same IRI, denoting the very same entity – can be used in both a predicate position and in subject position. It can even occur in both those positions in the same triple, as in the RDFS example I cited, or this (from  https://www.w3.org/TR/rdf11-mt/#rdfs-interpretations ): 

rdfs:domain rdfs:domain rdf:Property .

Note that both occurrences of the URI rdfs:domain denote the same thing, viz the domain property in RDFS, which relates properties to classes.
> Thus we turn to reification, which is what both Marilena and I propose above.
> 
> 
RDF reification (which is, and I speak as one of its designers, a total crock) makes RDF /assertions/ into objects which can be described in RDF. Reification does not provide any traction to describe RDF /properties/. 
> Or ... if you prefer the ABox / TBox distinction, properties are only individuals in the TBox layer.
> 
> 
That venerable distinction is invisible in RDF :-) All properties in RDF are individuals. 
> Or ... if you prefer the philosophy version, properties in RDF are True Universals and do not have Particulars.
> 
> 
In RDF, anything in the universe of discourse is a property, as well as a particular. Put another way, RDF denies the significance of this as a metaphysical distinction. This is a somewhat radical philosphical position, but it is internally coherent, conforms to a lot of linguistic data, and has a proven track record in practical ontology engineering. (The Web ontology standard OWL for example did not permit this in its first version, but the OWL 2 revision was modified to allow it.) If anyone is interested, I can mount a philosophical defense of it; my colleague Chris Menzel and I used a similar approach to develop the (vastly more expressive) ISO Common Logic semantics, and we have defended that in various publications. But this might be going a bit off track in this forum. 

Pat

**Comment by pjhayes** [comment]
> On May 8, 2019, at 7:51 PM, A. Soroka <notifications@github.com> wrote:
> 
> If I understand the disagreement correctly, suppose we have:
> 
> :thing :property :value1
> :thing :property :value2
> then we add something like
> 
> :property :hasQualification :qual
> we are saying that the qualification holds for both uses of :property in the predicate position.
> 
Indeed, you are saying that it holds for ALL uses of :property, anywhere on the WWWeb or indeed anywhere else. Which is why to try to add a qualification to an assertion by asserting it /of the predicate/ is a bad idea. (I tried to say this in the telecon today, but I fear I was not very coherent.) 
> This would be why you are saying that "RDF (and RDFS) syntax and semantics allows for properties to have properties”.
> 
No, I was saying that simply because it is true, and a useful aspect of the RDF design. I did not intend to imply, by making that observation about RDF, that to use a property of a property to qualify that property was a good ontological decision. It is not. 
> But if we would like to be able to make a qualification on one use of :property in the predicate position and not the other, things become much more complex for RDF (not for the property graph model).
> 
Well, I would not say it was /much/ more complex. One has to distinguish between a property and a particular situation or occassion of its holding true, and qualify the latter. Again, the terminological flexibility of RDF allows one to use the same URI to denote both the relation and the class of its holdings, which simplifies things somewhat. So

> :thing :property :value1
becomes

:thing :topic :holding1 .
holding1 rdf:type :property .
holding1 :object :value1 .
holding1 :hasQualificaiton :qual .

which is admittedly rebarbative, but conforms to a clear ‘pattern’ which can be searched quite efficiently. The new ‘locus’ node :holding1 can often be interpreted as referring to an event of some kind, especially when the qualification is a date. 
> That is why @azaroth42 <https://github.com/azaroth42> is saying "RDF and thus Linked Data does not allow for properties on properties".
> 
> 
But that assertion is simply false, as I have pointed out. What perhaps was meant was that RDF does not provide for adding qualifications to properties, but that is not quite the same claim. 

Pat
> I'm not sure if that helps clarify, but I'm starting out hopefully.
> 
> 
:-)

**Comment by Conal-Tuohy** [comment]
I think this is merely a terminological confusion. In the documentation of the CRM ontology (which Linked Art is based on), the term `Property` is defined thusly:

> A property serves to define a relationship of a specific kind between two classes. The
property is characterized by an intension, which is conveyed by a scope note. A property
plays a role analogous to a grammatical verb, in that it must be defined with reference to
both its domain and range, which are analogous to the subject and object in grammar
(unlike classes, which can be defined independently). It is arbitrary, which class is selected
as the domain, just as the choice between active and passive voice in grammar is arbitrary.
In other words, a property can be interpreted in both directions, with two distinct, but
related interpretations. **Properties may themselves have properties** that relate to other
classes (This feature is used in this model only in order to describe dynamic subtyping of
properties). Properties can also be specialized in the same manner as classes, resulting in
IsA relationships between subproperties and their superproperties.
In some contexts, the terms attribute, reference, link, role or slot are used synonymously
with property.

These so-called "Properties" are similar to RDF "Properties", but not identical, because of the existence of "properties of properties". When @azaroth42 made his original comment, it would be clear to those of us working with the CIDOC CRM that it was a reference to this feature of their model, since the phrase "properties of properties" is regularly bandied about in CRM discussion fora, with this particular meaning. The ambiguity of the phrase in the context of RDF is regrettable, but I am sure it does not reflect a misunderstanding of the substance of RDF's model on Rob's part.

**Comment by pjhayes** [comment]
> On May 9, 2019, at 3:32 AM, Conal Tuohy <notifications@github.com> wrote:
> 
> I think this is merely a terminological confusion. In the documentation of the CRM ontology (which Linked Art is based on), the term Property is defined thusly:
> 
> A property serves to define a relationship of a specific kind between two classes. The
> property is characterized by an intension, which is conveyed by a scope note. A property
> plays a role analogous to a grammatical verb, in that it must be defined with reference to
> both its domain and range, which are analogous to the subject and object in grammar
> (unlike classes, which can be defined independently). It is arbitrary, which class is selected
> as the domain, just as the choice between active and passive voice in grammar is arbitrary.
> In other words, a property can be interpreted in both directions, with two distinct, but
> related interpretations. Properties may themselves have properties that relate to other
> classes (This feature is used in this model only in order to describe dynamic subtyping of
> properties). Properties can also be specialized in the same manner as classes, resulting in
> IsA relationships between subproperties and their superproperties.
> In some contexts, the terms attribute, reference, link, role or slot are used synonymously
> with property.
> 

> These so-called "Properties" are similar to RDF "Properties", but not identical, because of the existence of "properties of properties”.
> 
Um…why? Both CRM Properties and RDF properties are understood intensionally, and both semantics permit properties of properties. They also both recognize the subProperty relationship and the connection to range and domain classes. So why can they not be identified?  I don’t see anything in the above CRM text which would require CRM to be incompatible with RDF in this regard (though there may of course be others.)
> When @azaroth42 <https://github.com/azaroth42> made his original comment, it would be clear to those of us working with the CIDOC CRM that it was a reference to this feature of their model, since the phrase "properties of properties" is regularly bandied about in CRM discussion fora, with this particular meaning. The ambiguity of the phrase in the context of RDF is regrettable
> 
The RDF usage is described in the RDF specs with mathematial precision, so ambiguity is hardly an issue there. 
> , but I am sure it does not reflect a misunderstanding of the substance of RDF's model on Rob's part.
> 
> 
As I authored the RDF semantics specifications and was an active member of both the RDF and RDF 1.1 working groups, I believe I can claim a certain authority regarding the RDF model. 

Pat

**Comment by ajs6f** [comment]
The discussion has become a bit abstract. I think it might benefit from attention to our purpose.

If @pjhayes could give us a worked example of the pattern
```
:thing :topic :holding1 .
holding1 rdf:type :property .
holding1 :object :value1 .
holding1 :hasQualificaiton :qual .
```
in the use case and setting in hand (relationships between resources for which we do not yet or may never have an explicit relationship in our model and specifically the student-teacher relationship with qualifications) we could then compile and compare the JSON-LD results for the various proposals and get a sense of the practical implications of each.

**Comment by Conal-Tuohy** [comment]
@pjhayes:
> Um…why? Both CRM Properties and RDF properties are understood intensionally, and both semantics permit properties of properties. They also both recognize the subProperty relationship and the connection to range and domain classes. So why can they not be identified?

In the CRM terminology a "property" is a class of relationship between two entities. But that phrase "property of a property" is to be understood not to refer to properties of that _class_, but to properties of _instances_ of that class; i.e. properties of _specific relationships_; it would be equivalent in RDF to a triple in which the subject is not an instance of rdf:Property, but rather an entire triple (reified as a subject). That is one ambiguity in the use of the term "property" in the CRM documentation: it is used to refer to both a class and to specific instances of that class. 

I'm not suggesting that RDF's definition of "Property" is ambiguous; rather that the phrase "Properties of properties" is ambiguous in _this discussion of both CIDOC CRM and RDF,_ since the phrase has been used to mean one thing in CRM documentation though it would mean another different thing in the RDF world. Hence when it's used "in the context of RDF", the phrase is ambiguous, whereas in a discussion of the CRM in which RDF is not in scope, the phrase's meaning is clearer. 

This terminological ambiguity is regrettable, but historically "properties of properties" is the phrase which has been used in the CIDOC CRM community, e.g. http://www.cidoc-crm.org/Resources/implementing-the-cidoc-conceptual-reference-model-in-rdf

I hope, Pat, that you now understand that the statement "properties of properties can't be implemented in RDF" is not a false statement reflecting a misunderstanding of the RDF model, but actually expresses a truth, using language differently to how it's used in RDF.

**Comment by Conal-Tuohy** [comment]
@pjhayes I posted a larger comment but then deleted it because I don't think this is really the place for a discussion of what the CRM documentation means by "properties of properties", except to say that it is indeed distinct from what that phrase would mean if "properties" were understand in the sense that RDF's model gives that term. May I suggest if you want to pursue that then you should start by familiarising yourself with how the "properties of properties" term is used in the CIDOC CRM literature? This might be a good place to start: http://www.cidoc-crm.org/Resources/implementing-the-cidoc-conceptual-reference-model-in-rdf

**Comment by ewg118** [comment]
Are we getting so far into the philosophical weeds that we're not able to practically implement relationships?

Are interpersonal relationships really in the scope for Linked Art 1.0?

**Comment by azaroth42** [comment]
Agreed. Looking at the design principles ... if we have shared use cases and data to support them, and the use case is generally considered to be valuable for linking art into the global graph, then we should aim for as simple as possible a solution.

And to return to the actual problem, as expressed, there isn't a way in CIDOC-CRM to assert that there is a relationship between two entities, where that relationship is not an existing relation in the ontology.  I think it would be out of scope and inconsistent to create a large number of relations for all the possible relationships between entities, in the same way that we do not create a large number of subclasses for all of the possible classifications of entities.

Lets exclude time as being intellectually interesting, but not something that has had a direct, shared need expressed for and a requirement for which we have other possible solutions (e.g. Phase). At which point I think we need go only as far as a simple class that has a `from` property, a `to` property, and allows `classified_as` / `P2_has_type` which would reference the `Type` of the relationship.

**Comment by ewg118** [comment]
This is a discussion that should be held within the broader community of prosopographers and people working on larger authority projects (like SNAC). I'm a proponent of a simpler model, with perhaps a single relationship property and class with the nature of the relationship expressed as a flexible and expandable list of instances (so the same data model can be applied across many different types of projects, from artists' relationships to dynastic structures of the Roman Empire), which is basically like @marilenadaquino's proposal. But these are complicated issues that don't necessarily relate to expressing an art object as linked data.

**Comment by azaroth42** [comment]
Agreement on the call of 2019-06-05 to close this issue and refocus.

**Comment by beaudet** [comment]
For what it's worth, NGA doesn't currently capture the relationships between constituents in our collection management system.

**Comment by pjhayes** [comment]
Hi Conal

Apologies for the very late response; I somehow missed your email when it was sent. 

I have read the CIDOC CRM standard in the link you provide, and see no evidence in support of your claim that the CRM sense of ‘property’ or ‘property of property’ is different in any important way from that used in RDF. The CRM is quite explicit, for example, in pointing out that classes and properties exactly correspond to unary and binary relations in standard quantified logic, which is also true for RDF. The CRM does not, it is true, actually state clearly what a property of a property is, but it does say that they are possible. If one interprets the first occurrence of ‘property’ as having the same meaning as when this word is used elsewhere in the document (and I see no reason not to), then this will be exactly the RDF sense. 

Best wishes

Pat

**Comment by azaroth42** [comment]
Agreement on the call of 06/05 that the issue has gotten out of hand. Closing.
