### ISSUE TITLE
Affiliating owners with object curation when exact order of ownership unknown

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#157]
The current model documents how to associate a sequence of owners in the lifetime of an object: http://linked.art/model/provenance/curation.html#individual-owners If I understand it correctly, this allows for a known sequence of owners without knowing the exact dates of transfer.

However, what if we have neither dates nor sequence? If our data asserts that a set of owners `a`, `b`, and `c` once owned the object, but it cannot assert whether `b` owned it before `a`, is it permissible to construct ownership activities _without_ `continued` and `continued_by`?

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-6f53da01789448039e0c14a4f4377ee9/page-1)

**Comment by azaroth42** [comment]
For owners without order, I can see two possible approaches:
  1. As you suggest, just create the curation Activity with the owner and object; 
  2. Create two Acquisitions, one that transfers ownership to the owner but doesn't have a seller or a date, and a second that transfers it away from the owner but doesn't have a buyer or a date.

Option 1. is more concise, and works with the semantics of "continued" -- the curation of the object is continued by the new owner.    Option 2. is more consistent with situations when we do know some of the other data, and more obvious as to what the sort of activities are.

The curation pattern is only really needed for the inventory taking activities, which otherwise wouldn't connect anywhere. Inventory is a weird activity for CRM as it doesn't change the state of the world, it provides evidence of the then current state. 

My preference would be create two Acquisitions without dates or other parties, rather than putting more weight on the way to manage inventory-taking. If we could find a better way to handle inventories, we might be able to remove that page completely.

**Comment by azaroth42** [comment]
The higher order question for this issue is how to discover the ownership assertion without a search? What links to this activity/state/thing/whatever?

**Comment by azaroth42** [comment]
Inventory taking is now an Encounter with the object (e.g. the object is encountered by some actor, and that encounter is important enough to document). The change of state of the world is the updated set of knowledge about the existence, ownership and location of the object.

As Encounters are part of the Provenance Activity wrapper, and Provenances can be related via temporal connecting relationships, this is now consistent with the rest of the model :)

**Comment by jpadfield** [comment]
Just curious how this might, in the future, fit on the spectrum of condition checking, and then on to physical interactions? 

Is the object there? - is it dirty? - has anyone touched it? - is it damaged? - Someone dusted the frame - ..... 

Will they be able to be classed as types of Encounters as well or will this shift to a new wrapper? And then how does this relate to the notion of imaging an object, or any other form of examination, given that taking an inventory is the simplest form of visual examination? 

Sorry, I know Linked Art is not specifically looking at Conservation or Scientific issues yet, but just thinking about future proofing and patterns.

**Comment by azaroth42** [comment]
This issue is documented here: https://linked.art/model/provenance/curation.html 

And the condition checks are now being discussed in the LCD context, to be documented in a separate conservation section of the model.

Closing :)
