### ISSUE TITLE
Color / Material permutations

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#184]
As Material is a controlled vocabulary exit point from the model, we cannot assign color to the material when that color is not part of the vocabulary directly.  For example, AAT has the concepts of [red chalk](http://vocab.getty.edu/aat/300080064) and [black ink](http://vocab.getty.edu/aat/300081180) very few other combinations of color and material. No yellow oil paint or purple watercolor.

The set of permutations would be impossible to manage, meaning that color (and shape) and material should be separate properties.

Thus to assert that there is white chalk and purple ink being used in a drawing, there would need to be parts of the object that have those properties:

```
{
  "label": "white chalk and purple ink drawing",
  "part": [
    {
      "classified_as": "aat:white",
      "made_of": "aat:chalk"
    },
    {
      "classified_as": "aat:purple",
      "made_of": "aat:ink"
    }
  ]
}
```

This seems like a lot of effort, and use cases should be presented before we add this to the model.

**Comment by natuk** [comment]
Not sure I understood the problem here. I think the AAT definitions for these few cases do not try to build permutations of colour and material. They are special cases of a material of specific substance which happens to be of a colour and the colour lends its name to them. So "red chalk" is a material not a material and a colour.
Also, if I am not missing the point, in CRM colour is a Feature of the painted surface, not a type of material. So the thing is made of Material "red chalk" and it has a Feature of type "red" (under daylight).

**Comment by azaroth42** [comment]
Per Thanasis, it is possible ... just verbose. Unless someone wants to present data supporting this, I propose we close. And even then I think the answer is already within our grasp - just partition and use the color/materials properties on the part.

**Comment by azaroth42** [comment]
Closing, no data to support implementation. If someone does have data to support this, we'll reopen it.
