### ISSUE TITLE
Identify best language vocabulary(s)

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#204]
Raised by @aisaac on WG call of 2019-01-30:

The current pattern for languages is to use a full resource to refer to the language, that can then be further described (such as that Castillian Spanish is narrower than Spanish, narrower than Romance Language, uses a particular character set, has these names in different languages, etc etc).

This replaced the more developer-familiar pattern of the 2 or 3 character ISO codes (BCP47, if I recall correctly) for the above reason, plus that there are many living and no-longer spoken languages that do not have those codes, and no useful way to add them.

For consistency, we should identify and recommend a particular vocabulary, as these language IDs will *need* to be consistent such that they can be used to present the right content to the particular audience. This would enable application level language negotiation, based on the JSON-LD, rather than #202 that would enable HTTP level language negotiation.

Related to https://github.com/linked-art/linked.art/issues/128#issuecomment-369787936

**Comment by beaudet** [comment]
These might be two different use cases.  Use case one is presenting potentially lengthy content that only matches a specific language, e.g. Castillian Spanish.  That might turn out to be better addressed by API searches rather than HTTP negotiation.  The second use case is presenting a response that uses syntax and labels that can reasonably be expected to be understood by most of humanity in the present day.  I think that's addressable by HTTP content negotiation.

**Comment by azaroth42** [comment]
Can this be closed, or is it still valid? I think the negotiation is a red herring -- the requirement is that language of content be associated with the content, and that consumers can do something useful with that information.

If a description has two materials statements, one in French and one in English, how would a UI know to present the right one to the user? It seems directly related to #186, and could be discussed in that context.

**Comment by azaroth42** [comment]
Closing in favor of #186
