### ISSUE TITLE
Name of influenced_by

### ISSUE THREAD

**Issue by ajs6f** [linked-art/linked.art#215]
At the 4 March meeting F2F @edgartdata, @marilenadaquino, and @lwoodruby mentioned that the term "influenced by" has a specific meaning in art criticism which _isn't_ the meaning assigned to `influenced_by` in our model. We should consider changing our nomenclature, or possibly reworking that part of the model.

**Comment by azaroth42** [comment]
To date, we have tried to keep the wholesale renaming of properties and classes to a minimum, beyond the computable changes needed for JSON and the correction of the collisions created by doing so and removing the numbers.

To change `influenced_by` is certainly possible, but it should reflect the relationship from the ontology, which is described as:

> This is a high level property, which captures the relationship between an E7 Activity and anything that may have had some bearing upon it.

Propose that we discuss this in github, and not on a call, as it's a naming question rather than substantive.

**Comment by ajs6f** [comment]
Between the two "audiences" of "people interested in art criticism" and "users of CRM", I would think we want to privilege the first, no? The overlap with a common meaning for the word _in the most specific domain_ seems to me more important than a conflict with a piece of more technical apparatus. Unless I misunderstood your meaning, @azaroth42?

**Comment by azaroth42** [comment]
I'm happy for confusing properties to be renamed. My point was mostly that we should do it in this issue, not on a call.  Proposals for new names?

**Comment by ajs6f** [comment]
@azaroth42 Is there any way we can link to the CRM-based definition of `crm:P15_was_influenced_by`? I can only find [huge docs](http://www.cidoc-crm.org/get-last-official-release). I can't find a way to link to our definition, either, but I'm probably overlooking something.

**Comment by azaroth42** [comment]
The CRM site doesn't have them all split out. The Erlangen version does, however:
http://erlangen-crm.org/docs/ecrm/current/index.html#anchor-273453507

And the scope note there is the same as in the current 6.2.6

**Comment by ajs6f** [comment]
It is extremely generic.

**Comment by azaroth42** [comment]
It's anything that has any "influence" on the event or activity. Suggestions for another name, or can we close the issue?

**Comment by ajs6f** [comment]
@edgartdata, @marilenadaquino, and @Lwoodruby, thoughts?

**Comment by marilenadaquino** [comment]
I don't remember that conversation, but I personally used [`influenced_by`](http://www.cidoc-crm.org/Property/p15-was-influenced-by/version-6.1) in a way it should reflect the meaning given by art critics (e.g.  the creation/production of an artwork is influenced by another artefact or person). My2cents,  I don't need to change name.

**Comment by Lwoodruby** [comment]
P15 has the definition used by art historians correctly, although very generically.  I've discussed with John McQuaid and we think in linked art, you would either need to use the more specific properties such as P134 continued P136 was based on P16 used specific object P17 was motivated by or use a different term, like school of, follower of, etc.

**Comment by edgartdata** [comment]
At the YCBA we agree with and follow the guidelines The Cataloguing Cultural Objects manual recommends to describe a work influenced by another. Note that we actually never use the term 'influenced by' because it is generic, as John and Louisa have remarked. In its place, we typically use one of the 4 specific attribution qualifiers below.
However, I also agree with Louisa that 'influenced by' is a shorthand that is widely used by art historians. 

Influenced by known creator (CCO definition): use one of the following qualifiers to indicate an influence (or an outright copy of) the style of the named master, but with the connotation that the named creator had little or nothing to do with the actual work at hand, The unknown creator need not necessarily be a contemporary of the named master (for example, style of Raphael or copyist of Rodin):

- style of: Use for a work by an unknown artist whose style is strongly under the influence of the style of the named master (e.g., style of Raphael).

- after: Use for a work by an unknown artist who has created a copy of a known work of the named artist.

- copyist of: Use for a work by an unknown artist whose style seems to be a deliberate copy of the style of the named artist, but when the work at hand is not a direct copy of a known work by the named artist (e.g., copyist of Rodin).

- manner of: Use for a work by an unknown artist whose style or elements of whose style are somewhat close to the style of the named artist, but whose work does not seem to be a deliberate copy of the named artist, and who generally lived in a period after the named artist.

(these last 4 definitions are from http://www.getty.edu/research/publications/electronic_publications/cdwa/14creation.html#Qualifier).

I guess my question is: how is Linked Art's use of 'influenced by' different from what's above?

**Comment by marilenadaquino** [comment]
I think Louisa and Emmanuelle are presenting two different aspects. 

I see in Emmanuelle's description a classification of _relations between two actors_ (the unknown artist and a named artist) that can be deemed true (a) only in the context of the creation of a new artwork (perdurant), or (b) more likely always, because s/he is anonymous (hence, a endurant entity). In case of anonymous artists I always preferred the second one, i.e. characterising the unknown actor as influenced by somebody known, and not the creation of an artwork influenced by some nuance of influence.

In Louisa's one I see (also/potentially/maybe -- sorry if I'm wrong) the characterisation of _relations between artworks_ regardless (?) the influence between actors, e.g. an anonymous drawing of Michelangelo's Last Judgment. In this case (possibly to avoid misunderstandings in the usage of CIDOC) I opted for reusing the PROV class [`prov:EntityInfluence`](https://www.w3.org/TR/prov-o/#EntityInfluence) to characterise the relation between the former artwork (the Last Judgement), the activity (the derivation), and the derivative/influenced artwork (the drawing). In this case I can easily infer and characterise also the relations between actors if needed.

My point is: `Influenced by` is totally fine to me, to the extent we know the possible values of the property.

**Comment by johnmcquaid** [comment]
Could we use influenced by to establish the link between two creators and then attach an appellation (copy of, manner of, etc) to define the type of influence when known?

**Comment by JamieBlu** [comment]
I’m not sure what the best way to encode the indie is but I have a need to encode artists and works that influenced another artwork 


 With best wishes,
--
Jamie Blustein, PhD
Assoc. Prof. of Computer Science & Information Management at Dalhousie Univ. (in Canada)
Director of HAIKU research group ▻ https://haiku.cs.dal.ca/
Dalhousie University Senator for Computer Science
On the WWW at https://www.cs.dal.ca/~jamie

Please note that this address uses servers hosted outside of Canada.

P.S.: I sincerely apologize if my message seems curt. I'm receiving too many messages to deal with each one as I used to. If you require more information about the specific content of my message please speak with me in person. For transactional messages I recommend an article in the Harvard Business Review at <URL:https://hbr.org/2016/11/how-to-write-email-with-military-precision>.


On Thu 09 Jan 2020 at 15:24 -05:00, johnmcquaid <notifications@github.com> wrote :

**Comment by Lwoodruby** [comment]
There are two points that should be made here: 
1. There is a difference between describing an artwork that copies a specific work of art (ie a drawing that copies Michaelangelo's Last Judgement, which is therefore done by a "copyist of Michaelangelo") and an artwork made by an anonymous artist whose general style is similar to that of a named artist (style of, follower of etc Michaelangelo). 
2. There could be MANY DIFFERENT artists who work "in the style of" or are "followers of" Michaelangelo.   These appellations were created to help sort large collections of unsigned works of art back in the early of days of art history and have continued today.  The auction houses actually assigned each one a hierarchical value of their proximity to the work of the artist. You can see this reflected in the definitions Emmanuelle provided.

**Comment by JamieBlu** [comment]
Is it worthwhile to do something similar for known artists?

 My specific instance is Kent Monkman's _Miss Chief's Wet Dream_ (2018):  Monkman (working with his atelier) deliberately used elements from Géricault's _Raft of the Medusa_ (1818–1819), was influenced by _Reid's Spirit of Haida Gwaii_ (1986) and refers (in the title) to event depicted in Rembrandt's _The Storm on the Sea of Galilee_ (1633).  Monkman did not contradict Annabelle Ténèze (AT) in a published interview when AT said that another element was inspired by Leutze's _Washington Crossing the Delaware_ (1851).

  I think it would be worthwhile to encode all of those relationships.
--
Jamie Blustein, PhD
Assoc. Prof. of Computer Science & Information Management at Dalhousie Univ. (in Canada)
Director of HAIKU research group ▻ https://haiku.cs.dal.ca/
Dalhousie University Senator for Computer Science
On the WWW at https://www.cs.dal.ca/~jamie

Please note that this address uses servers hosted outside of Canada.

P.S.: I sincerely apologize if my message seems curt. I'm receiving too many messages to deal with each one as I used to. If you require more information about the specific content of my message please speak with me in person. For transactional messages I recommend an article in the Harvard Business Review at <URL:https://hbr.org/2016/11/how-to-write-email-with-military-precision>.


On Thu 09 Jan 2020 at 12:52 -04:00, Emmanuelle Delmas-Glass <notifications@github.com> wrote :

**Comment by azaroth42** [comment]
To make sure that the discussion can continue without being lost when the current issue is resolved, I suggest that:

* We close this issue -- the naming of `P15_was_influenced_by` is not the *only* way that influenced by is used in an art historical context, nor are production influences the only things that could use P15, but they are overlapping in both directions and the name is pretty clear as to the intent of the relationship.

* We move the discussion about production qualifiers to #229, which is specifically about this topic

**Comment by azaroth42** [comment]
Agree can close this one and continue in #229.
