### ISSUE TITLE
Document details of TimeSpan model

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#239]
Although time, and hence the TimeSpan class, are of the utmost importance to art history, we do not currently explicitly document the model for TimeSpan. It is only implicitly defined in the activity examples, such as for [provenance](https://linked.art/model/provenance/).

Proposal:

The useful features are:
* `begin_of_the_begin` - the earliest possible datetime the timespan can start
* `end_of_the_begin` - the latest possible datetime the timespan can start
* `begin_of_the_end` - the earliest possible datetime the timespan can end
* `end_of_the_end` - the latest possible datetime the timespan can end
* `duration` - a `Dimension` that gives the duration of the timespan within the timeframe
* `classified_as` - potentially useful for "estimated" or "computed"
* `identified_by` - asserting a `Name` to display, per the normal pattern
* `_label` - an internal documentation label, per the normal pattern

Note that `duration` was until very recently `minimum_duration` and `maximum_duration` but it was rationalized into `upper_value_limit` and `lower_value_limit` on Dimension, to make the pattern more accessible to other use cases.

Diagram:

<img width="509" alt="timespan" src="https://user-images.githubusercontent.com/871868/59782142-2bc88780-9272-11e9-8631-a7ce8945a3e7.png">

Example:

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "http://lod.example.org/museum/TimeSpan/0", 
  "type": "TimeSpan", 
  "_label": "3 days during the 1970s", 
  "begin_of_the_begin": "1970-01-01T00:00:00",
  "end_of_the_end": "1980-01-01T00:00:00", 
  "duration": {
    "id": "http://lod.example.org/museum/Dimension/0", 
    "type": "Dimension", 
    "value": 3, 
    "unit": {
      "id": "http://lod.example.org/museum/MeasurementUnit/0", 
      "type": "MeasurementUnit", 
      "_label": "days"
    }
  }
}
```

(/ht @ajs6f)

**Comment by azaroth42** [comment]
Including the use of `Name` as a slot to put textual content to be displayed to end users.

**Comment by ncarboni** [comment]
The time model use datetime value with the range T00:00:00 till T23:59:59 ?
_example_:
```turtle
crm:E52_Time-Span ;
crm:P82a_begin_of_the_begin  "1401-01-01T00:00:00"^^xsd:dateTime ;
crm:P82b_end_of_the_end      "1401-01-01T23:59:59"^^xsd:dateTime .
```

or T00:00:00 till T00:00:00 of the next day?
_example_:
```turtle
crm:E52_Time-Span ;
crm:P82a_begin_of_the_begin  "1401-01-01T00:00:00"^^xsd:dateTime ;
crm:P82b_end_of_the_end      "1401-02-01T00:00:00"^^xsd:dateTime .
```
--
[We](https://docs.swissartresearch.net) are using the the range T00:00:00 till T23:59:59

**Comment by beaudet** [comment]
I think 23:59:59 is problematic because of the "missing second" between 59:59 and 00:00 or the requirement to make an assumption that 23:59:59.560 is equal to 23:59:59.  Time stamp calculations in databases and programming languages do not make that assumption yet times like that most definitely exist in data sources.

It seems less problematic to proceed according to the computation ( total time = end time - start time ) being mathematically correct.

That said, it carries its own disadvantages, particularly when the resolution of time used in display of the data is not the same resolution in which the data has been recorded.  For example, to convey "all of 2001" would require a start time of 2001-01-01T00:00:00" and end time of "2002-01-01T00:00:00".  Computationally, this gives exactly one year (all of the year 2001) regardless of time resolution and the expected computations will generally work.  

If the data is formatted as YYYY only and then displayed, it would be misleading, but I think this stems from needing a clear definition of "end time".  I would argue that the end time is one plank second AFTER activity ceases.  In that way, the computation total time = end time - start time continues to be true.

**Comment by azaroth42** [comment]
This is the issue that I raised with the SIG here:  http://lists.ics.forth.gr/pipermail/crm-sig/2019-May/003837.html

The answer seemed to be:  🤷‍♂ 

Given ease of searching, ease of creation, the leap second issue ... I'm in favor of midnight on the first, rather than the second before that.  e.g. Beginning is inclusive, end is exclusive.

**Comment by ncarboni** [comment]
>  However, if the data is formatted as YYYY and simply displayed, that would clearly be misleading.

It is exactly that. The only doubt I have is about the extraction of the year from datetime. If I query the following snippet:
```turtle
<https://resources.swissartresearch.net/person/birth/timespan/6a850e1b-b92f-46a0-adaa-4eff14aeb133> a crm:E52_Time-Span ;
crm:P82a_begin_of_the_begin  "1400-01-01T00:00:00"^^xsd:dateTime ;
crm:P82b_end_of_the_end      "1500-01-01T00:00:00"^^xsd:dateTime .
```
with 
```sparql
select (year(xsd:dateTime(?birthDate)) as ?birthYear) where {
  
  ?time crm:P82b_end_of_the_end ?birthDate.
}
```
I do obtain 1500 and I see this as a major issue, specifically because year extraction from datetime it is not such exotic activity

> I think we need a clear definition of "end time". I would argue that the end time is one planck second AFTER activity ceases. In that way, the computation total time = end time - start time continues to be true.

**Comment by azaroth42** [comment]
Yes, we ran into this as well ... that it looks like a range including the 1500s if all you do is show year-year. Don't do that then :)

**Comment by azaroth42** [comment]
Done here: https://linked.art/model/base/
