### ISSUE TITLE
Part removal which results in a new object

### ISSUE THREAD

**Issue by natuk** [linked-art/linked.art#257]
This came up at one of the modelling sessions in the London showcase. How do we model a part removal event which is also a production event for the part that has been removed. E.g. manuscript pages featuring miniatures have been removed from the manuscript and are held in a different collection as separate objects. Causation can be modelled with the O13 triggers property from CRMsci which requires two events (i.e. a part removal event causing the production event). The question is if this is semantically significantly different from the case when the part removal event is the same as the production event.

**Comment by azaroth42** [comment]
Or sampling for conservation or research, where we want to describe the object, the sample, its removal and the subsequent activities that affect either or both.

I think the model should be part of the provenance section, and use E80 Part Removal but without a Production -- the removed HMO's beginning of existence _as an entity in the documented system_ is the removal.  Otherwise it would look a lot like a Production, I would expect, but we should go through the information we have about removals.

**Comment by azaroth42** [comment]
Face to face discussion - part removal is sufficient for the use cases. If need to have a production, then it's part of the production of the original, not at the time of the part removal.

**Comment by aisaac** [comment]
[F2F 30 Jan](https://docs.google.com/document/d/1jBLE5hDYOeGTS0s9e7MzwHgNNEfMjC3jJW8Pk6na26A/): we agree the removal is not a production event. The production of a part (e.g. a leaf of a book) is the production of the whole, to which there is still a path leading. There could be a production event for the part, but then it would be the same modeling issue as if the part would still be in the whole.

**Comment by azaroth42** [comment]
Done: https://linked.art/model/object/production/#production-by-removal
