### ISSUE TITLE
Document design principles to ensure coherent direction

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#28]
Starting from:

* http://linked.art/model/index.html
* http://linked.art/model/jsonld/#context-design
* http://iiif.io/api/annex/notes/design_patterns/#design-patterns

**Comment by workergnome** [comment]
and to capture earlier conversations:  http://review.americanartcollaborative.org

**Comment by azaroth42** [comment]
Additional design principles:

* The human cost of understanding many classes and predicates is high, and we seek above all to minimize that cost while retaining sufficient accuracy to be useful

* The desired target model is (thus) the smallest profile of core CIDOC-CRM that captures sufficient information to describe demonstrably shared use cases. 
  * We will only introduce new features when there is a shared use case
  * We will only create new predicates and classes when there is no CRM way to do it
  * The cost of adding new features is considered to be high, and thus reusing common patterns is greatly preferred over adding new ones

**Comment by azaroth42** [comment]
* The basic use of fetching data into an application to render to a human is an important consideration, but not at the expense of poor semantic consistency or accuracy.

* Consumer-issued graph queries (via SPARQL or other technology) is a minor concern and should not influence design when a choice is being made. 

* Per scope notes, the following are (currently) out of scope:
  * Complex bibliographic descriptions
  * Data Provenance
  * Programmatic access to Uncertainty

**Comment by azaroth42** [comment]
Per @workergnome:

"we are defining patterns and models that enable cultural heritage memory institutions to easily publish their data for both event-based digital research projects and for use by non-cultural-heritage developers"

"we should use both shared models and shared software to augment the data.  Our goal is to reduce the complexity for publishers and consumers, while enabling researchers to access the full richness of the data"

**Comment by azaroth42** [comment]
In the linked.art model there should be clearly defined ways to do things, associated with graceful degradation strategies to go from more complex to less complex. As a community we will decide where the line between core model and extension lives on a case by case basis, based on extent of shared use cases that require the complexity and the ability of community members to provide data that fits within the shape.

**Comment by workergnome** [comment]
Another external source to review: https://collectionsasdata.github.io/statement/

**Comment by Conal-Tuohy** [comment]
@mdlincoln what's an "overlay" in this context?

**Comment by azaroth42** [comment]
The distinction here is between a model that requires the complexity in all cases, versus an overlay that can add to a simpler model without requiring it.  For example, the majority of cases for attribution will be simple `Production carried_out_by Person`, but if it's important to represent either who is asserting that, or previous beliefs that were later changed, we can use `AttributeAssignment` to overlay the simpler pattern without changing it. So the accepted or at least most recent attribution is in the carried_out_by pattern, others are added via assignment, rather than every assertion being reified to an assignment.

To try and express as a principle:  The relative frequency of the use cases should determine the amount of complexity required: simple solutions for the majority of the cases, but accept further complexity for additions for less frequent use cases. Additions should not change the simple model in order to avoid simple consuming implementations failing to include core features from complex descriptions.

**Comment by Conal-Tuohy** [comment]
I'm not sure I do follow this. I mean, I understand that the CRM includes a number of properties which are semantic "shortcuts" for more articulated statements. 

Ignore me if I'm sidetracking the issue. I know ... I'm poking my nose in here, trying to follow along as a matter of interest, but I'm not involved enough to understand some of the basis of what you are doing. Hence when you say "requiring", I'm not clear as to who or what is doing the requiring, and and who or what they are requiring things of. 

Does the principle just mean that for certain parts of the domain model, shortcuts _may_ be used? i.e. that they are allowed, but that for other parts of the domain model, long form statements would be _required_? Or does it mean that the longer form _may_ be used but that if it is, only certain long-form statements should be privileged to be encoded as a shortcut?

**Comment by workergnome** [comment]
I think what we're trying to say is that different data providers will have different levels of data specificity available, and different data **consumers** will want different levels of specificity in their data.   So, for a given concept (like Dimensions), I think there are two base patterns.  One is for a textual *description* of the concept:

```ttl
_:mmo  crm:P67i_is_referred_to_by _:dimensions_statement .

_:dimensions_statement a crm:E33_Linguistic_Object ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300266036> ;
    rdf:value "The painting is approximately 16 inches wide, by 20 inches high" .
```
This has no computer-parsability but allows the computer to retrieve and display that data for humans. The second base pattern is for computers:

```ttl
_:mmo crm:P43_has_dimension _:dim1, _:dim2.

_:dim1 a crm:E54_Dimension ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300055647> ;  # Width
    crm:P91_has_unit <http://vocab.getty.edu/aat/300379100> ; # Inches
    rdf:value 16 .

_:dim2 a crm:E54_Dimension ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300055644> ;  # Height
    crm:P91_has_unit <http://vocab.getty.edu/aat/300379100> ; # Inches
    rdf:value 20 .
```

Both of these are good CIDOC-CRM patterns, and they're mutually compatible.  But often we have data that includes, say, the width, framed and unframed, so we need to add complexity to our model to capture that: 

```ttl
_:mmo crm:P46_is_composed_of _:support, _:frame .

_:support crm:P43_has_dimension _:dim1, _:dim2.
_:frame   crm:P43_has_dimension _:dim3, _:dim4.

_:dim1 a crm:E54_Dimension ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300055647> ;  # Width
    crm:P91_has_unit <http://vocab.getty.edu/aat/300379100> ; # Inches
    rdf:value 16 .

_:dim2 a crm:E54_Dimension ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300055644> ;  # Height
    crm:P91_has_unit <http://vocab.getty.edu/aat/300379100> ; # Inches
    rdf:value 20 .

_:dim3 a crm:E54_Dimension ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300055647> ;  # Width
    crm:P91_has_unit <http://vocab.getty.edu/aat/300379100> ; # Inches
    rdf:value 18 .

_:dim4 a crm:E54_Dimension ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300055644> ;  # Height
    crm:P91_has_unit <http://vocab.getty.edu/aat/300379100> ; # Inches
    rdf:value 22 .
```

Or sometimes we'll want to record two measurements of the same thing, taken at different times:

```ttl
_:mmo crm:P46_is_composed_of _:support.
_:support P39i_was_measured_by _:measurement_1, _:measurement_2.

_:measurement_1 a crm:E16_Measurement;
    crm:P40_observed_dimension _:dim1, _:dim2;
    crm:P14_carried_out_by _:conservator.


_:measurement_2 a crm:E16_Measurement;
    crm:P40_observed_dimension _:dim3, _:4;
    crm:P14_carried_out_by _:registrar.
```

All of these are valid CRM techniques for expressing the same concept, just with increased complexity of modeling. Given that, how do we think about modeling in a way that doesn't (A) require us to model things at the most specific level possible, or (B) require consumers to check multiple graph shapes to find the same content?  

One technique is the **overlay**, where we can keep the base level in place and add triples to model that additional complexity without removing the base level.  That's the easiest option for consumers.

The other suggestion, for **extensions** is to say that there is a defined technique for each of the more complex patterns that will reduce it to the next-simplest pattern automatically.What we're working out is how to do this, both practically and as design principles.  I don't think this can always be done explicitly through inference or modeling (We'd might want, as an example, to choose the largest set of dimensions, or the one marked 'overall', or we might want to choose the most recent measurement, and those are hard to express as OWL constraints or as overlays).

This means that the publisher can choose the level of modeling specificity that they think is appropriate for their data, and the consumer can choose the level of API that best meets their needs, and the conversion between the two can be handled in software at the publisher/aggregator/API level, rather than every client writing multiple possible search patterns and selecting between them.  (They can still *do* that, but they don't *have to*.)

This also sets constraints on allowed community-defined patterns for complexity beyond what we've defined.  (Say, for example, my work on provenance, or a way to integrate IIIF into CIDOC-CRM).  If they either overlay the base pattern, or they can be automatically reduced to the base pattern, then consumers can choose to ignore them without losing access to the data, and adoption can be gradual.

*(obviously, this is still very theoretical, and we're talking through if it's both possible and a good idea.)*

**Comment by Conal-Tuohy** [comment]
Thanks for the clarification, which is helpful, though I'm sorry I'm still not sure I've grasped the precise content of the terms "overlay" and "extension", "base", and "core", though I more or less understand the context you're using them in. When you say

> One technique is the overlay, where we can keep the base level in place and add triples to model that additional complexity without removing the base level. That's the easiest option for consumers.

... by "base level", do you mean the ontologically simpler formulation? Or do you mean the formulation which the contributor has contributed to the aggregator (which might be simple or complex)? I'm kind of assuming the latter (although "**additional** complexity" suggests it might be the former).

In which case an "overlay" would be a set of additional statements which were derived (by the aggregator) from input statements, using some automated process, whether rule-based reasoning, or SPARQL queries or whatever?

> The other suggestion, for extensions is to say that there is a defined technique for each of the more complex patterns that will reduce it to the next-simplest pattern automatically.

When you talk about an "extension" implying the reduction of complex patterns to simpler patterns, it suggests that by "extension" you mean some ontological complexity which the aggregator is prepared to accept from contributors, but which it will reduce to a simpler pattern for the benefit of consumers who might prefer the simplified version. 

@mdlincoln contrasted the two (overlay vs extension) by reference to a "core"; is the idea that an ontologically complex contribution would be _replaced_ by a simpler formulation if the complexity fell outside the "core" (= if it's considered an "extension" to the "core"), whereas if the contribution's complexity was still within the "core", then any new formulation which the aggregator derived from it would be presented to consumers as an _addition_, rather than a _replacement_? Have I understood?

**Comment by workergnome** [comment]
By base level I mean an ontologically-simpler formulation.    

The overlay is an ontologically-denser formulation that can co-exist in the triples with the base-level without introducing inconsistencies in the model. 

so, for example:

```ttl
_:painting dct:subject _:concept
```

is a base-level definition for genre, but

```ttl
_:painting crm:P128_carries _:information_object .
_:information_object a crm:E73_Information_Object ;
    crm:P129_is_about _:concept .

**Comment by mdlincoln** [comment]
Re: https://linked-art.slackarchive.io/general/page-11/ts-1495218130246591:

If you can infer, do.

e.g. If an object is `classified_as: aat:lithograph`, then it should also be `classified_as: aat:print` and have `production: {technique: aat:lithography (printing technique)}`

**Comment by workergnome** [comment]
I think clarifying who "you" is is important here.  Again, I'm thinking of three distinct audiences here:  Publishers, Researchers, and Developers.   


Publishers should publish the most specific data they have:  `aat:lithograph`.   They almost certainly shouldn't try and publish the entity AAT hierarchy—that's the whole point of using an authority.    My personal preference, and I'm not sure that this is canon yet, is:

```

**Comment by Conal-Tuohy** [comment]
I agree! 

As a developer, I would certainly want to be able to query for prints and retrieve lithographs. To support that, the server would need to have either flattened those term hierarchies or be prepared to traverse them at query time (perhaps using SPARQL property paths). I think if you have a collection that makes use of one or more external vocabularies for classification, and you offer an API in which you can use those vocabularies, then you have to _own_ those vocabularies and be prepared to use them to expand users' queries. Otherwise each querent would have to be responsible for exhaustively expanding their queries to include all the narrower terms which you might possibly have, which I think would be a burden. Especially so if there are vocabulary alignments which would allow query terms to expand to terms in other vocabularies.

When it comes to accessing individual representations of particular resources (e.g. a graph about a particular lithograph), I don't think it is really essential to a developer that the classification terms are expanded. You could just include the URI for the term, or you could expand it out to include natural language labels, a link to the term's vocabulary, a label for that vocab, a linked list of `skos:broader*` relations, etc. The value of including the extra classification data depends on what the client is doing, I think. But if the client is basically a "resource-viewer" or browser, then having that information to hand may well be very useful (it might save a number of HTTP requests, in the case that an item had been classified by a large number of terms each of which were well down inside SKOS hierarchies). 

For large scale DH research, though, I think the way to go is to download a dump of the RDF you need and do your own inference with an OWL reasoner (such as inferring `skos:narrowerTransitive` from `skos:narrower` relations), or do the necessary inference in SPARQL:

```sparql
SELECT ?foo
WHERE {
   ?foo art:classified_as skos:narrower* aat:1234567
}
```

**Comment by azaroth42** [comment]
I've attempted to capture the discussion here:  https://linked.art/model/profile/ 
Comments welcome, of course!

**Comment by Conal-Tuohy** [comment]
Again, my comment is that the term "overlay" remains obscure, and the example still leaves me puzzled.

> "Overlays" are an important pattern, where the basic information is left in place and overlaid with more complex data. For example, the Production is `carried_out_by` the Artist, and previous attributions use `AttributeAssignment` to assert them, rather than requiring `AttributeAssignment` for all such attributions.

I interpret this to mean that only "previous" attributions are "required" to use `AttributeAssignment`, but that the "current" attribution should instead be asserted more directly. So the "current" attribution would be the "basic information" in the example, and the "previous" attributions would be the "more complex data" (though your example doesn't state this explicitly).

I think the phrase "is left in place" isn't helpful. It begs the question of who is "leaving in place" something which by assumption pre-existed, and who is "overlaying" the additional information which is in some way "subsequent" to the stuff which was "left in place". That first sentence implied (to me) that the `carried_out_by` assertion is "left in place" and would be overlaid with another (more complex) expression of the _same data_ (this would explain the implied temporal sequence of "leaving in place" while "overlaying"). 

But it seems to me that maybe you actually mean something else; that only statements which require some kind of qualification should be expressed in a "longhand" form, and that the "overlaid" complex expressions are logically independent of the "basic" expressions (i.e. they assert different things, rather than asserting the same facts in greater or lesser detail).

Cheers!

**Comment by azaroth42** [comment]
Fixed (I think ... feel free to reopen if it's still unclear)
