### ISSUE TITLE
How do we deal with the language of the (language) label?

### ISSUE THREAD

**Issue by thomashaensli** [linked-art/linked.art#319]
During todays presentation a naive questions pop to my mind: how do we deal with the language of the language label?

e.g.

> ... 
"language": [
        {
          "id": "http://vocab.getty.edu/aat/300388277", 
          "type": "Language", 
          "_label": "**English**"
        }
      ], 
...

could as well read

> ... "language": [
        {
          "id": "http://vocab.getty.edu/aat/300388277", 
          "type": "Language", 
          "_label": "**Inglese**"
        }
      ], 
...

Same question obviously applies to any "_label"

And last but not least: how do we proceed if we want to have "_label" in more than one language.

**Comment by ewg118** [comment]
I assume there's no rule against having more than one `_label`

**Comment by azaroth42** [comment]
Per previous call, we decided that unless anyone had any existing data where there were multiple languages for labels (rather than for actual Names), that we would leave this as a single string without an associated language.

The language and multiplicity issue should be documented when we talk about `_label`, so flagging this as editorial to do that.

**Comment by azaroth42** [comment]
Clarified here: https://linked.art/model/base/#core-properties
