### ISSUE TITLE
Aboutness: Depicts / Subject / Style ... ???

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#32]
In discussing aboutness, there is still more guidance needed as to which categories to put different topics.
Currently, we have something like:

* `depicted`: An identifiable thing or event that you can point to in the artwork. For example a portrait of a person, a depiction of a particular battle. The thing must be an instance, not a type or class.
* `subject`: A concept or class that is not actually depicted in the artwork, but is evoked by it. For example the atrocities of war, rascism, love, peace.  These are more why the thing depicted is portrayed. 
* `genre`: A stylistic technique present in the artwork that does not depict anything, it's how the depicted things are portrayed rather than what is portrayed.

Which excludes two important categories:

* The depiction of non specifics, such as a generic battle, a random landscape or person.
* Classification into categories such as still life, genre painting, portraiture.

One proposal is that depiction of non-specifics is added to `depicts` and that we add additional classification examples (such as those above) via `classified_as`.

The categories could then be defined as:

* `depicts` -- __what__ is depicted in the artwork that you can point to and say 'that is X' or 'that is an X' 
* `subject` -- __why__ the content in the artwork is present. You can point to the composition and say that it is about Y, which is a concept or idea.
* `style` -- __how__ the content in the artwork is presented. You can point to the composition and say that it is presented in a Z way.
* `classified_as` -- a class that has been assigned to the object based on the content and interpretation of the content.

[From discussions with Emmanuelle, Mathew, David, Ethan, and others!]

**Comment by mdlincoln** [comment]
(paraphrasing in from Slack)

Could we define `style` as aesthetic properties that transcend _strongly_ historically delimited classifications? (conceding that no aesthetic properties exist _a priori_ of culture/history) On the other hand, terms that are strongly historically delimited, or otherwise derive from art-historical (rather than museological) categories would instead fall under `classified_as`.

Two examples that are slightly slippery, but I think fall on separate sides of this division: 

1. "Impresisonism" as `classified_as`, rather than `style`: A painting that looks “impressionist” (parts of Vermeer’s _Lacemaker_) but was from c. 1669 (Vermeer’s _Lacemaker_) would never be called “Impressionist”. A [William Merrit Chase painting](http://www.metmuseum.org/toah/hd/chas/hd_chas.htm) might be `classified_as` "Impressionist", though, even though he was not associated with the birth of French Impressionism in the 1870s.
2. "Abstract" as a `style`, rather than a `classified_as`: While types of abstraction are tightly linked to certain historical moments (Suprematism, Cubism) and would fall under `classified_as`, "abstract" as a general aesthetic term could be used to describe renderings from a wide range of periods.

**Comment by cbutcosk** [comment]
Just so I can grasp these distinctions and since I've had artists' allusions on the brain lately:

- Do allusions (eg, [Manet](http://www.manet.org/images/gallery/olympia.jpg) and [Titian](https://en.wikipedia.org/wiki/Venus_of_Urbino#/media/File:Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg)) `depict`? The Manet probably has the Titian as a `subject`, yeah? 
- How about parodies (thinking the [endless](http://www.oberlin.edu/images/Art200-08/200-447.JPG) [parodies](https://olympia1865.files.wordpress.com/2010/05/catcariacture.jpg) of [_Olympia_](https://olympia1865.files.wordpress.com/2010/05/caricature-olympiabouquet.jpg))? Do caricatures `depcit` (parodically) or parody a `subject`?

Regardless they cover enough uses that these distinctions seem good enough to use in the wild--it feels like a lot will sort out in usage.

**Comment by workergnome** [comment]
Hmm.  I don't think that the Manet depicts the Titian—you can't point to it and say, "there's the other painting!"

I would say that the subject might be the Titian, but I think the right way to do this would be to say that the **creation** of the Manet `was_influenced` by the Titian.

**Comment by workergnome** [comment]
(Also, while we're on the subject, from my collection off Gnome paintings:)

![img_0711](https://cloud.githubusercontent.com/assets/34536/25587066/5b09a1f4-2e70-11e7-9085-465708167f14.jpg)

**Comment by mdlincoln** [comment]
Is it madness to allow a `type` attribute on a `was_influenced` construction, allowing someone to point to a vocab if they wish to specify the kind of influence, e.g. [`aat:allusion`](http://vocab.getty.edu/aat/300055815)

**Comment by mdlincoln** [comment]
There won't be a lot of these kinds of connections in existing data, but the ability to express relationships like this is an oft-repeated desire of art historians. If we can model relationships loosely enough to allow for different vocabularies of choice, that'd be great.

**Comment by azaroth42** [comment]
Style of school addendum discussion: https://linked-art.slackarchive.io/general/page-18/ts-1496940141743783

**Comment by azaroth42** [comment]
I think we're as good as we're going to get at the moment, following from #59. Closing, without assumption that this is done forever, just that we'll need a lot more input to make significant improvements from the current state.
