### ISSUE TITLE
professional activity vs profession

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#351]
In the person model, we have two options for how to express a profession, but neither are complete. They need to be aligned somehow.

We can use a professional activity (https://linked.art/model/actor/#active-dates) which currently does not give the type of activity, other than "professional". So the person carried out their unspecified profession at a certain time and place.

We can use a classification in the same way as nationality (https://linked.art/model/actor/#nationality) for profession, which does not give the time or place. So the person was a painter, and painted at an unspecified time and place.

Nationality and Gender are also temporally bound, but they are not activities with intent and thus cannot be carried out. To express temporality for these (and others) we need phases (#179, #180) which we are trying to avoid if at all possible.

Options:

* Make Professional Activity a meta-type and insert a specific type between the activity and the metatype:  Rembrandt carried out an activity, which is classified as painting, which is in turn classified as a professional activity.  This is my preference as it is consistent with other meta-typed unenumerable lists of types.

* Just add painting (etc) on to the professional activity as a second classification.  I don't like this, it makes for two patterns ... a list of types and a hierarchy of types ... and we've gone with the hierarchy approach (see also brief text / description).

* Just use a meta-typed classification on the person without the activity node. I don't like this because we very frequently have dates and places for the activities.

* Use a Phase for the classification.  I don't like this because we've done very well at avoiding it, and there are other options above that would let us continue to avoid it.

**Comment by ncarboni** [comment]
Make Professional Activity a meta-type seems to be the best and most harmonious way to achieve this

**Comment by illip** [comment]
Following your modelling choices, I would also vote for the meta-type option. However, I'm wondering how you will model active dates when you don't know the specific professional activity? Like in your example on the website:

> Patrick Q. Robertson was active between 1910-01-01 and 1934-03-21

Would you have some kind of generic type? What would be the semantic difference between the type and the meta-type in this situation?

**Comment by azaroth42** [comment]
I can't think of a good way to do this without two classifications.

The same way that we have "artwork" as a classification for the art object itself, and then "type of work" as a classification for the big bucket of object types, perhaps we're in the same position with this. If we don't know the type of activity, we still want to classify it as being the "professional activity". And then there's a big bucket of types of activity that could be considered professional, which could benefit from a meta-type.

**Comment by ncarboni** [comment]
The only problem I see with this solution are the temporal boundaries. Normally such type of statements are simply expressing that someone was known to be an architect/painter/etc. , but they do not carry temporal boundaries. 
Would the construct 
```ttl
<https://linked.art/example/person/11> a crm:E21_Person ;
crm:P14i_performed <https://linked.art/example/activity/11> .

<https://linked.art/example/activity/11> a crm:E7_Activity ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300393177> .

http://vocab.getty.edu/aat/300393177> a crm:E55_Type ;
    rdfs:label "Professional Activities" ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300024987> .

<http://vocab.getty.edu/aat/300024987> a a crm:E55_Type ;
    rdfs:label "architects" .
```
be OK without temporal boundaries?
Also, maybe my latin roots speaking, but wouldn't the word "occupation" instead of "profession" be more general in scope?

**Comment by azaroth42** [comment]
That wouldn't work if 393177 is used for multiple activities of different sub-types. Then "architects", "photographers", "painters", etc would all be associated with 300393177, and it would be impossible to distinguish which activity went with which specific type.

I'm thinking this pattern is maybe as good as we can get:

```
{
  "type": "Person",
  "performed": {
    "type": "Activity",
    "classified_as": [
      {"id": "aat:300393177", "type": "Type", "_label": "Professional Activities"},
      {"id": "aat:300024987", "type": "Type", "_label": "Architecting", "classified_as": {"id": "aat:type-of-activity", "type": "Type", "_label": "Type of Activity"}}
   ]
}
```

Which mirrors the artwork + painting - object type pattern in Physical Objects.

**Comment by azaroth42** [comment]
Discussion on call -- it would be good to call out the search pattern for "artists" etc. in the documentation.  

Connect from professional activity to exemplar activities via `part_of` ? Issue remaining about production as part_of a professional activity, as neither are top level in the API.

**Comment by illip** [comment]
I discussed this issue with my team and I would like to add our thoughts here. Sorry if it's a little long.

# Needs clarifications regarding Rob's last diagram

1. What could be a "type-of-activity" in this previous diagram? It cannot be something like "Leisure Activity" or "Professional Activity" since "Architecting" should be under solely one metatype throughout the model. According to this, the metatype of "Architecting" could be something like "Construction Activity".
2. Could more than one professional activity reside under a single general one? If so, the model will not accept different dates for each profession if they are described in the input dataset.
3. Is "active dates" considered to be equivalent to "professional activity"? Following the current pattern, this will be taken for granted. However, at least in Canadian collections, it is often not the case that the active dates always represent the professional period of someone (since active dates may include activities such as scholarship or volunteering).

# Requirements

Linked.Art must manage 4 requirements:

1. Record the active dates of someone without knowing his or her particular profession.
2. Record the profession of someone and the period of time during which he or she was performing it.
3. Record a metatype of the profession to enable grouped requests (e.g. Construction Activity).
4. Record sub-activities like a specific production related to the profession.

# Postulates

1. The active dates should be explicit in the data, meaning that it will not be determined through inferencing processes.
2. If the data mention a time-span for each distinct profession, the system must allow us to record it.
3. The system should not use the same concept as a type and a metatype in order to simplify querying.
4. Types should always reside under the same metatype, if not there is no way to know which metatype should be used with the typed entity.

# Use case

Person X was a painter from 1830 to 1842 and became a sculptor in 1842 until 1854. He or she is a well-known painter due to painting Y done in 1832. Thus, an active period from 1830 to 1854. 

# Modelling

Following the aforementioned sections, here is a proposal to represent those requirements based on Linked.Art’s structure and what CHIN is working on for its Collections Model:

```
<https://linked.art/example/person/X> a crm:E21_Person ;
    crm:P14i_performed <https://linked.art/example/activity/A> ;
    crm:P14i_performed <https://linked.art/example/activity/B> ; # Required?
    crm:P14i_performed <https://linked.art/example/activity/C> ; # Required?
    crm:P14i_performed <https://linked.art/example/activity/D> . # Required?

<https://linked.art/example/activity/A> a crm:E7_Activity ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300393177> ;
    crm:P82a_begin_of_the_begin "1830" ;
    crm:P82b_end_of_the_end "1854" ;
    crm:P9_consists_of <https://linked.art/example/activity/B> ; 
    crm:P9_consists_of <https://linked.art/example/activity/C> .

<https://linked.art/example/activity/B> a crm:E7_Activity ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300025136> ;
    crm:P82a_begin_of_the_begin "1830" ;
    crm:P82b_end_of_the_end "1842" ;
    crm:P9_consist_of <https://linked.art/example/activity/D> .

<https://linked.art/example/activity/C> a crm:E7_Activity ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300025181> ;
    crm:P82a_begin_of_the_begin "1842" ;
    crm:P82b_end_of_the_end "1854" .

<https://linked.art/example/activity/D> a crm:E12_Production ;
    crm:P108_has_produced <https://linked.art/example/object/Y> ;
    crm:P82a_begin_of_the_begin "1832" ;
    crm:P82b_end_of_the_end "1832" .

<https://linked.art/example/object/Y> a crm:E22_Human-Made_Object ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300033618> .

<http://vocab.getty.edu/aat/300025136> a crm:E55_Type ;
    rdfs:label "painters (artists)" ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300025103> . # Required?

<http://vocab.getty.edu/aat/300025181> a crm:E55_Type ;
    rdfs:label "sculptors" ;
    crm:P2_has_type crm:P2_has_type <http://vocab.getty.edu/aat/300025103> . # Required?

<http://vocab.getty.edu/aat/300025103> a crm:E55_Type ;
    rdfs:label "artists (visual artists)" .

<http://vocab.getty.edu/aat/300393177> a crm:E55_Type ;
    rdfs:label "active (professional function)" .

http://vocab.getty.edu/aat/300033618 a crm:E55_Type ;
    rdfs:label "paintings (visual works)" .
```

**Comment by azaroth42** [comment]
Thanks @illip!

To the questions - I don't think we should try to express a full hierarchy of types, but instead just to have a single metatype per pattern. Essentially this is the "facet" in AAT terms -- the highest useful classification before it would be ambiguous with other patterns.  So if the type was "writing poetry", then there could be any number of intermediate broader concepts before getting to the API-intended "type-of-activity".  A search system could then fill in as many broader terms as is would be useful without getting in the way of the meta-type. Some systems might want to group "poet" and "author" together under "writer" and then that all writers are under "artist", whereas others might only use "author" for the writers of technical documentation and not consider it as art at all. Thus "architect" and "author" and "artist" and all the other innumerable types would all have the same "type-of-activity" metatype, but could have different broader terms in different systems.

For (2) ... is the intent that you want to have a single "active" period with its own timespan, that then has potentially overlapping parts for when the various types of activity were performed? Seems like a good use of the partitioning pattern, as you have in your example.

For (3) ... I don't think we need to circumscribe very precisely the exact nature of the activity. If a lawyer works on a case pro bono and thus doesn't get paid, is that still a "professional" activity? If an author writes a very bad poem, and then later takes up writing books, is the poem the start of the "professional" work even if not well received? I think those sorts of decisions are up to the publishing institution, not the model.

For the requirements, I agree with 1 2 and 4, but (per q 1 above) I think that 3 is the role of the vocabulary not the model. 

I agree with postulates 1-4, and thus the metatype needs to be as broad as possible while not colliding with other metatypes.  Thus "activity type", parallel to "work type" and "statement type".

**Comment by azaroth42** [comment]
Propose defer to 1.1 or 2.0 -- the issue is when we know active dates but not what sort of activities they were. Equally, there's likely to be many different sorts of professional activity carried out during the time.

**Comment by azaroth42** [comment]
2024-05-01: 
Multiple organizations with data for this, so should solve.

No metatype on the specific classification. Make professional activities recommended in #186.
Future self problem if there are other classifications that aren't role type.
