### ISSUE TITLE
Curation page in the documentation is not rendered well

### ISSUE THREAD

**Issue by michielhildebrand** [linked-art/linked.art#363]
https://linked.art/model/provenance/curation.html

**Comment by azaroth42** [comment]
Yep, thanks for the reminder!  The page needs rewriting as we're trying to avoid the use of Phase (which is why it doesn't render properly)

**Comment by michielhildebrand** [comment]
I was afraid of this. We build upon this in Van Gogh Worldwide. We like to display when an artwork was owned by someone. Do you advise to move to the model using the buying/selling activities instead of the ownership phases?

**Comment by azaroth42** [comment]
Apologies, both for the bad news and the for the delay in responding!

Yes, as much as the Phase approach is useful circumstances like this where an event or activity otherwise doesn't have any other connections, the activities should be the core of the data.  The Phases were an attempt to provide structure to the overall ownership data, but quickly get complicated when the provenance entries affect multiple objects at the same time.

I think this is an area where we need to look to implementations (such as yours!) to inform what signposting and structure is needed to make those provenance entries more accessible.

**Comment by vangoghworldwide** [comment]
We are considering the switch to the transfer-based approach. I will keep you posted about the shortcomings (if any) of this approach.

**Comment by azaroth42** [comment]
Fixed by removing the page completely as unnecessary and outside of the CRM scope
