### ISSUE TITLE
Create minimal context for faster parsing

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#410]
The current context can take a while to parse and use, given its length and the number of scoped contexts. It includes all of CRM base, even the properties and classes that we don't use.

There should be an optimized version (and to discuss whether that should be the default) that has only the classes and properties that are used in the profile to reduce this implementation cost.

[c.f. rubensworks/jsonld-context-parser.js#34]

**Comment by azaroth42** [comment]
Kicking it down the line. Can be done at any time.

**Comment by azaroth42** [comment]
Bumping it back up the line as this is a blocker for VGWW and other Jena users.
Should also document the bug in Jena for folks who run into it later.

**Comment by michielhildebrand** [comment]
The ticket in Jena https://github.com/apache/jena/issues/2551#issuecomment-2188422392

This ticket is closed as the jsonld handling is done by an external library titanium-json-ld. I reported the bug there https://github.com/filip26/titanium-json-ld/issues/348. This is marked as won't fix due to lack of funds.

We did not have time to check if we could provide a pull request to the library.

**Comment by azaroth42** [comment]
closing again as we found and solved the issue :)
