### ISSUE TITLE
Assertion of a non-value

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#423]
Possibly out of scope for Linked Art generally, but worth considering... how can we make a positive assertion that something does not exist? In particular, in the distributed LOD scope, it is useful to know which systems have been considered in the search for external identifiers for an entity and found that there weren't any. 

For example, we might know a lot about a person depicted in an artwork, but they're not in any external dataset like ULAN, VIAF, LCNAF, wikidata, and so on. If they have a common name (say Charles Smith) then it would be valuable to record that we know they are not in those datasets, and to not try and automatically find a match for them.

This could be accomplished with an AttributeAssignment like this:

```
"attributed_by": [
  {
    "type": "AttributeAssignment",
    "classified_as": [{"id": "some-uri-to-flag-as-a-null-assertion"}],
    "carried_out_by": [{"id": "uri-of-person-or-organization-making-assertion"}],
    "timespan": {"type": "TimeSpan", "_label": "date of checking"},
    "used_specific_object": [{"id": "uri-of-vocabulary-checked"}, {"id": "uri-of-vocabulary2-checked"}],
    "assigned_property": "identified_by"
  }
]
```

**Comment by ajs6f** [comment]
https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/

:)

More seriously, does making a negative assertion about the world jibe with the OWA?

**Comment by azaroth42** [comment]
That is indeed the issue -- it's hard (impossible?) to distinguish between "I positively know that there isn't an identifier in this system at this time" and "I do not know if there is an identifier in this system at this time" without getting into modeling belief. I think generally it does, so long as the modeling is about what was done, not the absolute state of the world -- "I checked and did not find an identifier" rather than "there is no identifier" -- and hence the value of `AttributeAssignment` here as an activity, rather than a reification of a triple.

**Comment by ajs6f** [comment]
No, I'll buy that (asserting the activity), anyway. We might need to unpack the reference to an external dataset to version or otherwise qualify it, but not unless/until use cases.

**Comment by azaroth42** [comment]
Closing. This seems like internal description workflow and documentation, not in scope for LA.

**Comment by cbanks-code** [comment]
Reopening this five years on, from practice rather than theory, because the thread reached the right place and then parked it.

The line in this thread that holds is Rob's: the modeling has to be "about what was done, not the absolute state of the world." A record saying "I checked and did not find" is a statement about the record and the party keeping it, and under the open-world assumption it does not conflict with a second record that later supplies the value; it is superseded by it. That is the whole of the trick, and it is enough to make the pattern safe.

Where the 2021 sketch stopped was the vocabulary. "Null assertion" is one state, and one state decays into a binary known/unknown flag within a month, because null is where unresolved things go. What a reader needs is the reason there is no value, and there are four that license different actions: unknowable (the fact cannot be recovered by anyone; stop looking), not applicable (the question does not arise for this object; stop asking), not yet obtained (the fact exists and has not been collected; this is work, and the entry should name who can close it), and never required (the question is not proper to ask here; do not ask). The completeness test is that each state licenses a different action; a vocabulary whose members produce the same behavior is one state wearing four names. SARI's five flags in #256 are cousins of this but sit on a different axis (how good is the value we have) rather than this one (why is there no value at all).

I have published this as an open specification for provenance records with declared absence (Lacuna, v0.5, CC BY): https://www.objectsofaffectioncollection.com/lacuna, concept DOI 10.5281/zenodo.22063353. The Linked Art shape it implies is exactly the 2021 sketch: an AttributeAssignment carried out by a documented party at a documented time, assigned_property naming what was sought, no assigned value, classified_as one of the four, with a note stating why. No new class, no new property. Withholding (a value known and deliberately not disclosed) is a separate case and is not in this vocabulary.

I have raised the same question with the CIDOC CRM SIG this week for the CRM side. If Linked Art would document the pattern as a profile or a "how to" even while keeping it out of core scope, I will write the page and the example against a real museum entry, and take correction on it. If the 2021 decision stands, that is a complete answer too.
