### ISSUE TITLE
Question: maintaining type information between AAT concepts and CIDOC-CRM?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#457]
Hi all,

Linked Art uses Getty's AAT whenever possible, using `rdf:type` to make clear that a concept in the AAT is a `crm:E55_Type`.

For example, for the concept 'Painting' ([source](https://linked.art/model/object/production/#base-production-activity)):

```json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/54",
  "type": "HumanMadeObject",
  "_label": "Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
    }
  ]
}
```

The Linked Art datasets that I am working on contain a lot of such references to AAT concepts, including the type information. However, as far as I know the AAT concepts - at the source - aren't typed as `crm:E55_Type`. Is this correct? If so, is there a best practise for maintaining these statements, i.e. that some AAT concept is a `crm:E55_Type`? For example:

a. I could create a separate linkset for these statements (e.g. `aat:300033618 a crm:E55_Type`). I could then use the information in this set when generating the Linked Art for the individual resources in our datasets.
b. Is there a common linkset in the Linked Art community that already contains these statements?
c. Or am I thinking in the wrong direction?

Thank you!

**Comment by beaudet** [comment]
I think the terms used to capture art object "classifications" should (?) be sub typed with the AAT's "visual work material or type" term from AAT, http://vocab.getty.edu/aat/300191091

**Comment by sdevalk** [comment]
Hi @beaudet, thank you for taking the time to respond!

Your example contains three `classified_as` resources in which a `type` property is used, pointing to AAT terms. I was wondering: how/where do you maintain this 'knowledge', i.e. the fact that `http://vocab.getty.edu/aat/300133025`, `http://vocab.getty.edu/aat/300033618` and `http://vocab.getty.edu/aat/300435443` are of type `crm:E55_Type` (and perhaps also that each of these terms have a certain `_label`/`rdfs:label`)?

In our Linked Data datasets we have numerous references to these - and other - AAT terms. We prefer to only store the IRIs of these terms (e.g. `http://vocab.getty.edu/aat/300133025`) in our database, and add the additional information (`type` and `_label`) when generating the full Linked Art representation of our data. But the question then is: what is the source of this additional information - how do we know that e.g. `http://vocab.getty.edu/aat/300133025` has type `crm:E55_Type` and has label `works of art`?

We could get this information on the fly, by resolving the AAT IRIs and fetching the types and labels in the response. This works for the `_label`: each AAT term has an `rdfs:label` that we can use. However, this doesn't work for the `type`: an AAT term is of type `gvp:Subject`, `skos:Concept` and `gvp:Concept`, but not `crm:E55_Type`.

We could store this type information in a separate dataset. This dataset could be very small - it would only have to contain AAT IRIs and their CIDOC-CRM type. We could then use the information in this dataset when generating our Linked Art. However, I'm not sure whether this is a sound approach.

How do you handle this?

**Comment by azaroth42** [comment]
There's an alternate end point for the vocabularies that expresses them as Linked Art / CIDOC-CRM:
  https://data.getty.edu/vocab/aat/300404655

The label can be just the `skos:prefLabel` ... or it could be something else entirely from a linked art perspective. `_label` is only for people looking at the JSON, not for rendering to end users.

The harder part is the type. They _could_ all be just `E55_Type` but AAT also has Languages, MeasurementUnits, Currencies and Materials in various facets, which would be good to project the records into. For example English is a Language (and Language is a subclassof Type), but concepts that are not languages aren't valid for the language of a linguistic object.

For entries that we use programmatically, I just keep them in code: https://github.com/linked-art/crom/blob/master/cromulent/vocab.py There's also #186 -- which is a long outstanding issue to define a minimum viable thesaurus, as to what is required, what recommended, and then to have other useful terms easily accessible.

**Comment by ewg118** [comment]
It doesn't really matter in practicality. Strict adherence to CIDOC-CRM means never using external vocabulary systems because those vocabulary systems are authored in SKOS. Simply extend your code or your SPARQL query to accommodate the model of the knowledge organization system instead of jamming square pegs into the CIDOC-CRM round hole.

**Comment by wouterbeek** [comment]
There is a difference between the data that @sdevalk and @beaudet are using [1] and the data that @azaroth42 is using [2] (@azaroth42 mentions this already, but I want to stress this for clarity):

```
[1] http://vocab.getty.edu/aat/300404655
[2] https://data.getty.edu/vocab/aat/300404655
```

The data exposed at [1] does not include any CRM typings, but the data exposed at [2] does include such CRM typings.

Observations:
1. If you use Getty AAT flavor [1] then you have no Getty-mandated CRM typings. If you want to use CRM you can add such typings yourself (some people seem to do this), but this is not best practice. In Linked Data it is Getty who decides what their IRIs mean. Somebody else can add meaning to that, but this meaning will always remain local and now shared with the community (e.g. dereferencing a Getty AAT flavor [1] IRI will not return potential CRM typings that others have added in their local repositories).
2. If you use Getty ATT flavor [2] you have Getty-mandated CRM typings. You do not have to add meaning that may or may not be mandated by Getty. Dereferencing Getty IRIs of this flavor includes the CRM typings, so they do not only live in somebody's local repository.
3. Getty currently publishes two flavors of what seems to be the same AAT thesaurus: flavor [1] without CRM typings, and flavor [2] with CRM typings.  This is a bit confusing to naive users.

Remaining questions:
1. What is the status of the two Getty AAT flavors?  Is [1] the old version, and is [2] the new version?  Since [1] and [2] are not the same IRI it is difficult for naive users to understand which flavor they should use.
2. Since LA mandates the use of AAT and CRM, is it correct that Getty AAT flavor [1] should not be used in combination with LA, and that only Getty AAT flavor [2] should be used in combination with LA? If somebody uses LA + Getty AAT flavor [1] then there is a disconnect because the flavor [1] IRIs are not typed with CRM. This will result in people adding they own local CRM typings (people already seem to do this today), which is not best practice in Linked Data.
3. Following (2), is it correct that most examples on the LA website are out-of-date, since they (exclusively?/mostly) use Getty AAT flavor [1] IRIs (e.g. <https://linked.art/model/place/>).

**Comment by beaudet** [comment]
Excellent points and questions. Seems we definitely need to get to the bottom of this and be clear about which direction to take.

**Comment by azaroth42** [comment]
My best and unofficial guesses as to the answers:
1.  As far as I know, the `data.getty.edu` mapping is a beta representation of the vocabularies to be useful in the CRM / linked art usage context, and not an official representation of the vocabularies. I don't know when, or even if, they will be available from the official URIs at `vocab.getty.edu` nor by what mechanism (though I would imagine content negotiation). I expect that they're waiting for Linked Art to hit 1.0, lest they publish something and then we change the model / api to make it invalid.
2. I don't think we can say that either is "correct", only that we have found [2] to be more useful. If there is general community agreement around this, then perhaps that will influence the Getty in making them more official :) 
3. We use the official URIs for the concepts, regardless of the representations that can be retrieved directly from them. I don't think we should change these, as they're widely in use around the community and world.

**Comment by wouterbeek** [comment]
@azaroth42 Thank you for the added information. The next step seems to be to align the Getty and LA initiatives (to avoid that either party waits on the other). Are the relevant people who can initiated this conversation already in this thread, or do we need to ping somebody?

> We use the official URIs for the concepts, regardless of the representations that can be retrieved directly from them. I don't think we should change these, as they're widely in use around the community and world.

This is an important point: pending the communication/alignment between Getty and LA, current users of Getty and LA should use the official AAT URIs (flavor [1] in my earlier message).

**Comment by azaroth42** [comment]
The vocabs now publish Linked Art natively, e.g. https://vocab.getty.edu/aat/300194222.jsonld 

I think we can close?

**Comment by azaroth42** [comment]
@sdevalk (or others) please feel free to reopen if this is still a concern!
