### ISSUE TITLE
Question: modeling the current creator of an artwork?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#475]
Hi all,

My dataset consist of metadata of artworks. It contains information about the artists that created these artworks, both the current artists and the artists we previously thought were the creators.

I can model this information with Linked Art using the ['Base Production Activity'](https://linked.art/model/object/production/#base-production-activity) for current attributions and the ['Uncertain or Changing Attributions'](https://linked.art/model/object/production/#uncertain-or-changing-attributions) for rejected attributions.

However, the dataset is rather nuanced. It doesn't say that artwork A has been produced by artist B. Instead, it says that curator C thinks it has been created by artist B. I'd like to express these nuances. Is this possible with the Linked Art patterns?

For example: can I use an `AttributeAssignment` (`crm:E13_Attribute_Assignment`) for this? In the Linked Art examples this is mostly used for recording previously believed values. But can I also use it for recording currently believed values?

The model could look like this:

```json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/61",
  "type": "HumanMadeObject",
  "_label": "Painting",
  "produced_by": {
    "type": "Production",
    "assigned_by": [
      {
        "type": "AttributeAssignment",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/...", // Some concept that expresses the current status?
            "type": "Type",
            "_label": "Current"
          }
        ],
        "timespan": {
          "type": "TimeSpan",
          "begin_of_the_begin": "2019-01-12",
          "end_of_the_end": "2019-01-21"
        },
        "carried_out_by": [
          {
            "type": "Person",
            "_label": "Paintings Curator"
          }
        ],
        "assigned": [
          {
            "type": "Production",
            "carried_out_by": [
              {
                "type": "Person",
                "_label": "J. Artist"
              }
            ]
          }
        ],
        "assigned_property": "part_of"
      }
    ]
  }
}
```

What are your thoughts?

Thank you.

**Comment by azaroth42** [comment]
I would recommend against doing that, as you'll end up reifying all of the knowledge in your dataset into AttributeAssignments.  You *could* do that... but will you or anyone else be able to actually use it for anything?  If it's current thought, just use the regular form. If it's obsolete, use the attribute assignment form.

**Comment by sdevalk** [comment]
Hi @azaroth42 Thanks! I fully understand your recommendation.

Is there a way to express additional information about current thoughts without having to use AttributeAssignments? For example: the curator that says that artist A is the (current) creator of some artwork?

Ideally I'd like to have one pattern for modeling both current and previous ('obsolete') thoughts, to make it easier for data consumers to work with the data - but I'm not sure if that's feasible (given the distinction between the regular form and the attribute assignment form).

**Comment by beaudet** [comment]
Rob, would you mind giving a simple example of what reification means in this context? I've seen the term tossed around in API and spec documents but I don't think I have a firm grip on the concept yet.  The Wikipedia entry describes it as a fallacy of logic involving conflation of reality with the model.

**Comment by azaroth42** [comment]
Reification is making something that is not a thing into a thing - in this case a relationship.  From the latin word for thing, "res" and from whence we get "republic" -- res publica, the thing of the people.

So (in short hand, to explain in context) instead of `object has_current_owner group`, `has_current_owner` becomes a thing with its own properties. In our case, an AttributeAssignment activity:

```
object attributed_by relationship_assigning
relationship_assigning a AttributeAssignment
relationship_assigning assigned group
relationship_assigning assigns_property has_current_owner
```

Which is necessary if you want to assert other knowledge about the relationship, such as

```
relationship_assigning carried_out_by curator
relationship_assigning classified_as current_knowledge
relationship_assigning timespan [botb 2000-01-01 ; eote 2001-01-01 ]
```

Thereby solving @sdevalk's use case, but at enormous cost. The cost is, hopefully, obvious:  Instead of one triple in the group / property on the json object, it turns into many properties that express the same thing as the single triple/property with some additional information about the provenance of that particular assertion. And then ... you start to do it for _every_ property and you end up with

```
x a HumanMadeObject
attributed_by [
  1 a AttributeAssignment ; assigned_property identified_by ; assigned {a Name, content "Name"}
  2 a AttributeAssignment ; assigned_property identified_by ; assigned {a Name, content "Name 2"}
  3 ...
  1000 ...
]
```

And we lost every last scrap of usability for the data from a developer's perspective. The first thing they're going to do is write a function that runs through the attribute assignments and turns them back into properties on x. Quite beside the additional weight of all of those AttributeAssignment nodes in the graph/document.

Or ... you could do both the regular form and the reified form, and pay the cost of the AttributeAssignments as well as the cost of the direct properties. 

The issue to me is one of scope -- is there any *consumer* for the reified form other than the producer of the data? If not, then there's no need for interoperability. And if there's no need for interoperability ... then it's not a linked art problem to solve. I don't think there's a consumer here, and even if there were, I don't think the added value justifies the cost.

**Comment by sdevalk** [comment]
I'm closing this issue. Thanks again, Rob! @beaudet Feel free to re-open if you have additional questions.
