### ISSUE TITLE
Activity.part has been replaced by part_of ? 

### ISSUE THREAD

**Issue by paulgirard** [linked-art/linked.art#486]
Hi all,

I am working on a linked-art data publication about artists education at Beaux Arts Paris (19th century). I will raise a few questions and comments in the coming days/weeks.

First thank you for this initiative!

In the multiple venues example https://linked.art/model/exhibition/#multiple-venues an activity has a part field which is an array of activities.
I can't find this in the JSON-Schema definitions only the ```part_of``` which is the other end of the link.

Did I misunderstand something?

**Comment by paulgirard** [comment]
Actually for my case it will be much easier to have the part instead of part_of in activity.
Would this means to add a ```part``` definition in the core.json Activity object:
```json
"part": {
      "description": "A list of one or more `Activity` structures, which are parts of this `Activity`",
      "type": "array",
      "items": {
          "$ref": "#/definitions/Activity"
      }
  }
```
And in the event.json too actually I guess.

**Comment by azaroth42** [comment]
Welcome :)

Yes, the model documentation has fallen a little out of sync with the API decisions. We decided to only use `part_of`, to go from the many to the few (e.g. many parts are each part of one (typically) whole), when designing the API from the model. The boundary conditions are described here: https://linked.art/api/1.0/principles/#division-of-information 

So multiple activities which are part of a larger one (such as venues within a multi-venue exhibition) would use `part_of`, rather than the `part` properties in the model documentation.  

I'll try to carve out some time to update the examples in the model pages to match the API where there are diffences.

**Comment by azaroth42** [comment]
All the examples now use API conforming JSON :)
