### ISSUE TITLE
Question: modeling relationship between persons and organizations?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#497]
Hi all,

I’m modeling a dataset with biographical information of artists and using the [Actors pattern](https://linked.art/model/actor/) as foundation. My dataset contains a number of relationships between the artists and organizations. For example:

1. Artist A ‘studied at’ Academy B (during a certain timespan)
1. Artist A ‘was a teacher at’ Academy C (during a certain timespan)
1. Artist A ‘was a member of’ Association D (during a certain timespan)

I’m wondering: how should I model these relationships (preferably using Linked Art constructs)?

For example:

1. I could use Linked Art’s [Organization Membership](https://linked.art/model/actor/#organization-membership) pattern for this. However, the examples do not use timespans, e.g. that Artist A was a member of Association D from date X to Y — so I’m not sure if this is an appropriate pattern.
1. I also could use Linked Art’s pattern for [Collections over Time](https://linked.art/model/collection/#collections-over-time). The pattern is geared towards objects, though. Is it also usable for persons?
1. Or should I use CIDOC-CRM’s `E85_Joining` (and `E86_Leaving`) for this?

Thanks!

**Comment by azaroth42** [comment]
We did this at the Getty by using Joining and Leaving with a classification.

e.g. Artist A joined Academy B, and that joining was classified_as <student> (and then leaving to get the timespan).

This allows individuals to participate in multiple ways with the same organization at the same time -- perhaps they're a student AND a teacher. 

1 - Yes, this is the simplest form. A was a member of B (at some point, and with some role)
2 - This is the object form of ...
3 - ... joining and leaving, which is what I would do.

(Also this issue is an implicit vote for Phases :) )

**Comment by azaroth42** [comment]
--> discuss and then document as this seems like a useful pattern to be clear about

**Comment by sdevalk** [comment]
@azaroth42 Thank you! :)

**Comment by azaroth42** [comment]
Also https://github.com/linked-art/linked.art/issues/237

**Comment by azaroth42** [comment]
Closed by #588
