### ISSUE TITLE
Exhibition idea ... InformationObject?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#498]
We don't use PropositionalObject anywhere else. And the notion of the exhibition is somehow symbolic?

**Comment by bluebinary** [comment]
I have no objection to using `InformationObject` (`E73`) instead of `PropositionalObject` (`E89`) for modeling the Exhibition idea document if we felt it was the right way to go. Given that `InformationObject` is a "subclass" of and inherits from `PropositionalObject` we don't lose any compatibility with existing modeling patterns, and can continue to use all of the same properties, and I believe all the semantics hold too.

Unless client code was checking the `type` key of the retrieved JSON-LD to ensure it was reported as `PropositionalObject` or somehow relied on the `type` key for another purpose, I would be surprised if there was a noticeable impact from the change. I am curious as to why the Exhibition idea document is the only current area of the Linked.art model that uses `PropositionalObject`; aside from the Linked.art model, are we aware of other uses of CRM for modeling Exhibitions that use something other than `PropositionalObject`, and if so, what have others seen or used as the alternative? Have some used `InformationObject` already?

Lastly, does the fact that `InformationObject` also inherits from `SymbolicObject` (`E90`) – in addition to inheriting from `PropositionalObject` – cause any unintended side effects that staying with `PropositionalObject` would not, particularly from a semantic standpoint? Does the notion of the Exhibition have to be considered symbolic somehow for it to be modeled using an `InformationObject`, or could that be incidental or only apply in some cases rather than all, due to the multiple inheritance of `InformationObject` which seems to suggest it is as much a `PropositionalObject` as it is a `SymbolicObject`?

**Comment by azaroth42** [comment]
The original reason for PropositionalObject was to ensure that it wasn't confused with the LinguisticObject for the exhibition catalog, but still needs to have a creator and subjects. E.g. CuratorX who conceived the exhibition is the creator of the propositional object. The "J M W Turner Paintings" exhibition is about Turner, and his paintings" Even if there was never an exhibition that actually took place, the conception still happened, so there can be a conceived exhibition without an Activity to go with it. The same conception could be used for travelling exhibitions, so multiple activities.

But I've never seen PropositionalObject used anywhere else, it's normally just part of the hierarchy that merges back Symbolic and Propositional at InformationObject. So if we can avoid introducing a very infrequently used class, that seems worth the slight semantic mismatch to me.

**Comment by cbutcosk** [comment]
@azaroth42 Is there any model documentation on the exhibition catalog pattern you're referring to? Exhibition collaterals seem more complex than will fit in a `LinguisticObject`. Or is the `LinguisticObject` you're referring to above a synposis of the catalogue?

**Comment by aisaac** [comment]
A bit of a side question, but maybe it can help progress by looking at a more general problem... 

I don't think the Collection pattern currently has a motivation for its Creation event, the way there is one in the Exhibition pattern. I'm not calling for one right now, but still, collection activities can have motivations that are not so different from exhibition ones (Martin Doerr used to talk about a 'unity criteria' for collections, which sounds applicable to exhibitions too). 
So could we have a solution that could be applied to both?
If yes, then we're looking for a class that can type the motivation for many activities, not just exhibitions. Is there a class that's used for "motivations" in CIDOC-CRM? It feels like the kind of philosophical question that would have been considered there.

And a much mundane remark: at https://linked.art/model/exhibition/ currently both the concept and activity are labeled "Example Exhibition". Would it be possible to make them distinct?

**Comment by azaroth42** [comment]
Decision - stick with PropositionalObject, create a new API endpoint called "Abstract Work" which is just PropObj.

**Comment by azaroth42** [comment]
Also great for other non-materialized "works" such as Performances (ala theatre, etc)

**Comment by azaroth42** [comment]
classified_as should be recommended - aat:300417531

**Comment by azaroth42** [comment]
Problem... to say that a LinguisticObject or VisualItem is `part_of` an Abstract Work (such as for the FRBR / LRM / BibFrame style modeling of Work (Abstract) --> Instance (Textual) --> Item (Physical) means that either we have a second property `conceptually_part_of` or we have to make Abstract Work an `InformationObject`, as the current mapping of `part_of` for LO/VI is to P108, which is from Symbolic Object rather than Propositional Object. 

So we need to pick one of:

* Abstract Work's `type` is "InformationObject" and the property is `part_of`
* Abstract Work's `type` is "PropositionalObject" and the property is `conceptually_part_of`

I prefer the new property approach as it more clearly separates `chapter part_of book`, from `book part_of general-concept-of-the-work`.

**Comment by azaroth42** [comment]
Most consistent is to have a single property for conceptual partitioning: `conceptually_part_of`

**Comment by azaroth42** [comment]
Closed by #676
