### ISSUE TITLE
resource dc:relation resource

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#5]
to get to generic related objects, without specific relationships

**Comment by azaroth42** [comment]
Is there a better relationship to use? I don't think there's one in CRM and dct is already in the set of ontologies used.  `related` as JSON key for http://dublincore.org/documents/dcmi-terms/#terms-relation ?  Applies to anything.

**Comment by workergnome** [comment]
Works for me—it's what we've been using at CMOA.

**Comment by Conal-Tuohy** [comment]
There was a relevant discussion on the CIDOC CRM list last year: http://lists.ics.forth.gr/pipermail/crm-sig/2016-September/002815.html

The question was about representing such semantically weak associations in CIDOC-CRM. There was one good suggestion, in my opinion, if your goal is to be able to give a complete description within that ontology (whether or not you also represent it with properties drawn from ontologies like DC). 

The idea is to model the set of generic relationships which an object has as an Information Object (I.e. a sequence of records of the DB's link table is directly modelled). You could even give it an Appellation "Related Objects". Then the Information Object can use "P67 refers to" to list the related objects. It's a bit prolix, but it at least provides a way to assert the relationship within the CIDOC vocab.

**Comment by workergnome** [comment]
So, when I think about these relationships, I think of, say, "has met", in the meaning of `_:david <has_met> _:rob`. This is a painful, painful thing to model in the CRM—I believe you'd either:

1. Create an event in which we met, that happened sometime during the mutual span of our lives, where we were both participants, and which has a p2_type of "Meeting", (somehow distinguished from the beuracratic sense).  
2. Create two Groups, one of "people David has met", and one "people Rob has met", and then add each of us to the other's mutual group as current_or_former_members, and the come up with some way to describe the semantics of that group.

Given that both of these are somewhat prolix (what a useful word), and that there are so many types of generic relationships, I lean heavily on the suggestion of using a custom predicate.  And given that I'd much rather import a custom predicate from an existing ontology than coin my own, `dct:related` seems like a good option.  (and, after doing some research, `rdfs:seeAlso` is also another good option.)

**Comment by Conal-Tuohy** [comment]
I think has_met is a bit different in that its semantics are a lot more precise than the common case of 'related', which I've seen in the wild myself and I assumed was the same beast you're talking about here. My comment was directed more specifically at the kind of relation that's carried by dct:relation. It's hard to be precise about what some museum curator thought constituted one of these generic 'relations'; still less to generalise the meaning of a bunch of such relations. In the discussion thread I cited, owl:topProperty was put forward, but that's clearly weaker than it needs to be. I think dct:relation is exactly right, myself, and I think rdfs:seeAlso is pretty close. Personally I might be inclined to a polyglot approach of exposing all three (crm, dct, rdfs) expressions at the LOD layer.

**Comment by workergnome** [comment]
Oh, I agree that `has_met` has more precise semantics than `dct:related`.  I think what I'm acknowledging is that  `has_met`, along with `corresponded_with`, or `discussed`, or `after_the_style_of` or `parodying` all have semantics that could possibly be modeled, but that the effort of modeling all of them explicitly both makes it hard to author and hard to query.  There needs to be some sort of shortcut predicate that allows me to aggregate these things, as well as something that allows me to express a relationship without needing to expend the energy to model that relationship in all its semantic glory.

**Comment by azaroth42** [comment]
Thinking at an API level for a moment, if the objects related to the current object are in a set, that set could be more easily provided via a separate API call.  For example:

```
{
  "id": "current-object-uri",
  "type": "ManMadeObject",
  "part_of": {
      "id": "current-object-related-set-uri",
      "type": "PhysicalThing", 
      "classified_as": "aat:related-objects"
  }
}
```

And then deref `current-object-related-set-uri` to see what its `parts` are. 

Thoughts?

**Comment by workergnome** [comment]
I still think that there's a use for a shortcut mechanism.

```
{
  "id": "current-object-uri",
  "type": "ManMadeObject",
  "dct:related": [
      "http://example.com/object/id/1",
      "http://example.com/person/id/2",
      "http://example.com/event/id/3",
      "http://example.com/website/id/4",
  ]
}
```
seems useful, but I'm also OK with there being a real entity that is that list of related things.  From the API point of view, it's messy either way, because we either need per-type relationships, or we need to dereference the objects anyway to understand what they are.  

From my API design background, we'd typically do this by shipping at dictionary of related objects with a subset of information with this as a sidecar:

```
{
  "data": {
    "id": "current-object-uri",
    "type": "ManMadeObject",
    "dct:related": [
        "http://example.com/object/id/1",
        "http://example.com/person/id/2",
        "http://example.com/event/id/3",
        "http://example.com/website/id/4",
    ]
  },
  "included": [
    {
      "id": "http://example.com/object/id/1",
      "label": "useful thing",
      "type": "ManMadeObject"
    },
    {
      "id": "http://example.com/person/id/2",
      "label": "Important Person",
      "type": "Actor"
    },
    {...}
  ]
}
```

If we tried to do this inline, we'd still need to capture that type info.  Being able to dereference that list could be useful (see, say, VIAF's [Just Links](http://outgoing.typepad.com/outgoing/2012/05/just-links.html) API endpoint, but it does add very dynamic and dynamically-generated entities per-object.

**Comment by Conal-Tuohy** [comment]
In response to:

> [has_met, along with corresponded_with, or discussed, or after_the_style_of or parodying all have semantics that could possibly be modeled, but that the effort of modeling all of them explicitly both makes it hard to author and hard to query](https://github.com/azaroth42/museum-lod/issues/5#issuecomment-287639436)

Yes, you would need to expend additional effort to model the semantics of your source data more richly than just using `dct:related`, but this needn't at all make it "harder to query" the data, because it doesn't at all preclude _also_ modelling those relations as `dct:related`. There really is no "either/or", here. You can do both, and in my opinion you should aim to also support richer semantics where you can afford to expend the necessary effort in modelling time (which in most cases would not be significant, it seems to me), and where the "semantic resolution" of the source data is adequate to support the richer model.

The semantic shortcuts of `dct:relation` can be very useful as a shallower representation of the data, that affords a "browsing" behaviour by end users, and I think it makes perfect sense to represent the data in that way. But please don't be too narrowly focused on that one use case! Richer semantics can be very useful for other purposes; particularly for DH researchers trying to find meaningful patterns in cultural data. For myself, personally, as a potential querent of this LOD, I would very much like to be able to traverse relationships of "influence" (such as your "parody of" example), in a directed sense (i.e. as an asymmetric relation), and for that purpose, the CRM shortcut property [`P130 shows features of`](http://erlangen-crm.org/docs/ecrm/current/index.html#anchor-1754121962) (or a custom sub-property "parodized") would be perfectly valid, and much more useful than `dct:relation` by itself.

**Comment by workergnome** [comment]
Yup.  And we're talking through @azaroth42 and my constant discussion, which is, "At what point in the pipeline from _Primary Source -> Mapping -> ETL -> Graph Data -> API -> Entity Document -> Client_ do we instantiate shortcuts, inferencing, class traversal, and things like that?" 

Particularly given that discovery, display, browsing, search, and research are all valid needs, and many of them have conflicting requirements?

**Comment by azaroth42** [comment]
To make progress on this issue, I propose that we accept `dct:related` on E1_CRM_Entity for the situation where there are relationships captured but without any further semantics.  If we know that there are 10 "related objects" but don't know why they were related, we can do no better than `dct:related` anyway.

For more specific relationships perhaps between more specific classes, we should follow the process and collect use cases, followed by investigating how much information is available in common data management systems.

**Comment by azaroth42** [comment]
Done ... reopen if there's anything else we need to do.
