### ISSUE TITLE
Alignment of intellectual and physical hierarchy in Archives

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#502]
In archives, there are two competing and overlapping hierarchies - the intellectual arrangement and the physical location of the items. This is a modeling issue because the items which participate in those hierarchies are also frequently not identified or described individually.

I think we can boil the modeling issue down to the following:

<img width="480" alt="archive-set-container" src="https://user-images.githubusercontent.com/871868/207636817-91b39251-dbbd-418c-bc2f-49a1f49cb897.png">

There are intellectual sets (which have items and other sets as their members), and there are physical containers that often have some relationship to the intellectual sets. The HMOs (or Digital Objects) are then within those sets and containers.

We're looking for a way to describe the relationship between the container object (folder, box, shelf, room, etc) and the set (series, fonds, sub-fonds, etc) which may not be one to one.  The vanilla description I just from conjoining the predicates would be something like: The Human Made Object holds or contains one or more items which are the members of the Set ... so `contains_members_of` ?

This seems related to `exemplary_member_of` and other properties that relate to a conceptual thing (represents_entity_of_type, etc) where there isn't an identity for an intermediate more specific node.

**Comment by azaroth42** [comment]
Rob to model Yale Archives Space data.
Richard to model V&A.
Julien to look at photo archives.

To discuss and compare at a following call.

**Comment by atiro** [comment]
Some examples from the V&A with many thanks to our archivists for finding some obscure edge cases (I hope they are edge cases anyway):

1.     [AAD/1982/2 : AAD/2019/3 : AAD/2019/9](https://www.vam.ac.uk/archives/unit/ARC51259) C. E. Kempe archive (ARC51259). Items dispersed over different boxes due to size throughout the archive ([ARC194974](https://www.vam.ac.uk/archives/unit/ARC194974)), but also some are now held at another site for Conservation work and were not returned to archive site during building work ([ARC195058](https://www.vam.ac.uk/archives/unit/ARC195058)). This is also an example of where later accruals have been intellectually integrated with former accessions in the catalogue but have not been integrated physically (e.g. [ARC194928](https://www.vam.ac.uk/archives/unit/ARC194928)) . 
2.      [AAD/1984/1](https://www.vam.ac.uk/archives/unit/ARC45992) Arthur Cecil Edwards and Clara Cary Edwards archive. The papers and photographs are at one site and the negatives are stored offsite. E.g. in series EDWARDS-3 ( [ARC106094](https://www.vam.ac.uk/archives/unit/ARC106094)),  the contents of sub-series EDWARDS-3-1 ([ARC107772](https://www.vam.ac.uk/archives/unit/ARC107772)) is stored at the V&A and the contents of EDWARDS-3-2 ([ARC107773](https://www.vam.ac.uk/archives/unit/ARC107773)) are off-site
3.     [AAD/1978/2](https://www.vam.ac.uk/archives/unit/ARC51256) etc Heals archive. Sub series HEAL-3-2 shows a mixture of random numbering (where the numbers don’t run in numerical order in the catalogue but do in the physical arrangement) and later accruals being slotted in to the intellectual (but not physical) arrangement ([ARC194226](https://www.vam.ac.uk/archives/unit/ARC194226))
4.    [AAD/1980/2](https://www.vam.ac.uk/archives/unit/ARC40121) Dorothea Braddell. An example of intellectual files being split due to size of material -see location note in this record ([ARC15798](https://www.vam.ac.uk/archives/unit/ARC15798)). 
5.     [THM/497](https://www.vam.ac.uk/archives/unit/ARC65627) Felix Dennis OZ Magazine Archive.  Items dispersed due to size but in same store eg. THM/497/12 (whole series) [ARC99495](https://www.vam.ac.uk/archives/unit/ARC99495)
6.     [THM/245](https://www.vam.ac.uk/archives/unit/ARC66776) William Huston Rogers Archive.  Items stored offsite eg. THM/245/2 Nitrate Negatives (series record [ARC117669](https://www.vam.ac.uk/archives/unit/ARC117669)) THM/245/2/2 Bette Davis Negatives (file) [ARC121360](https://www.vam.ac.uk/archives/unit/ARC121360)
7.     [THM/399](https://www.vam.ac.uk/archives/unit/ARC5813) Glastonbury Festival Archive.  Mixture of traditional paper archives and born digital archives. Eg. Ann Cook Photographs (series – 145 digital items) [ARC204195](https://www.vam.ac.uk/archives/unit/ARC204195)
8.     [BMT Overtures](https://www.vam.ac.uk/archives/unit/ARC102764).  Items on display eg BMT/2/1/2 Abbacadabra [ARC102767](https://www.vam.ac.uk/archives/unit/ARC102767)

**Comment by julsraemy** [comment]
# Photographic archives of the SSFS

I have three main cases from the [photographic archives of the Swiss Society for Folklore Studies (SSFS)](https://archiv.sgv-sstp.ch/). Each of these cases is part of a different collection that we are investigating within the [PIA research project](https://about.participatory-archives.ch/). 

| **Case**                                             	| **Collection**                                    	|
|------------------------------------------------------	|---------------------------------------------------	|
| Photographs in an album                              	| ```SGV_10 Familie Kreis```                        	|
| Negatives in a box                                   	| ```SGV_12 Ernst Brunner```                        	|
| Variety of object types belonging to the same series 	| ```SGV_05 Atlas der Schweizerischen Volkskunde``` 	|

**Storage**

All photographic archives are currently stored at Spalenvorstadt 2 in Basel, Switzerland. 

**Linked Art Entities**

For positive photographs, the main entity being modelled is the `HumanMadeObject`; for negatives the main entity is its digital (positive) surrogate counterpart. More information here: https://github.com/Participatory-Image-Archives/linkedart/

## Case 1: Photographs in an album

The Familie Kreis collection comprises around 20,000 loose photographs taken between 1850 and 1980. A quarter of them were organised in 93 photo albums.

![la-entities-overview-alignment_01 drawio](https://user-images.githubusercontent.com/17925031/220331192-aa79e531-2f74-431c-8acb-cc572ab73bfd.png)


## Case 2: Negatives in a box

The archive holds over 47,000 black and white negatives in 6x6 cm format by the photographer Ernst Brunner. There is metadata for all of these images, arranged in several boxes according to a numerus currens broadly according to the date of photography from 1937 to 1962.

![la-entities-overview-alignment_02 drawio](https://user-images.githubusercontent.com/17925031/220331694-0c5ad4aa-efef-45ce-8948-1201df2457a4.png)

## Case 3: Variety of object types belonging to the same series

The data was collected in the 1930s and 1940s and the results were published between 1950 and 1995 in the form of a cartographic atlas with comments. In addition to the maps and comments compiled by the researchers, there is also material collected throughout the surveys, such as photographs and drawings, which are organised in different boxes. 

It should be noted that this collection is currently being digitised and that after completion there will be a repackaging of certain objects to put them in conventional boxes and store them in suitable climate-controlled rooms according to archival standards.

![la-entities-overview-alignment_03 drawio](https://user-images.githubusercontent.com/17925031/220331716-193eb40f-fc70-4d45-a931-7910a6b70143.png)

**Comment by Habennin** [comment]
This is what we did in SARI and followed for AIC at PMA:

https://docs.swissartresearch.net/et/archival/

**Comment by aisaac** [comment]
A comment while reading @julsraemy 's example: someone may see the shelves more as locations than as "archive container", if the box(es) could be moved and the physical hierarchy would remain be the same. So the boxes could be the subject of the contains_members_of statements.
Where I'm coming at is that if there's a hierarchy of "contains/holds/hasPart" I'm not sure where contains_members_of should be stated. Maybe one could decide to state them as every level, because well, every level except the last one do contain some members of the collection. Unless the definition for the property explicitly says that it should always be the "top level container" (a resource that's not typed as a place)?

(and a more specific question to @julsraemy : do you really want to say that your "intellectual sets" have both physical and digital items as members? I mean, maybe you can say it, but it offers an opportunity to digress into discussing what the sets should be, which is perhaps not the core question here ;-) )

**Comment by julsraemy** [comment]
@aisaac for your specific question regarding physical and digital items: it was just an attempt to show that negatives are treated differently in our data model but indeed this wasn't necessarily useful for this issue/modelling exercise.

**Comment by azaroth42** [comment]
Agreed about different options for where `contains_members_of` could be associated. I think that level of detail will come in time, and probably be different for different situations, based on how the archive is described in the underlying system. I think the important thing is that we need such a property to link the intellectual and physical arrangements, and there isn't one in CRM at the moment. 

I think it's reasonable to say that both physical and digital objects can be arranged intellectually into a single set. This is one of the advantages of la:Set over crm:CuratedHolding (previously called Collection) ... it isn't just physical.

**Comment by azaroth42** [comment]
* yes to adding contains_members_of for 1.0
* seems to be sufficient for the use cases discussed

**Comment by azaroth42** [comment]
Done
