### ISSUE TITLE
embedded structure MUST annotate incomplete transclusions

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#507]
To ensure the reference / pointer is recognizable, and clients don't inadvertently follow links (etc)

**Comment by azaroth42** [comment]
Send to the mailing list, but F2F5 thinks this is a good one -- the least bad option.

**Comment by beaudet** [comment]
For clarity, are you talking about not including IDs for embedded structures of particular types such as first class LA entities?

For example, there is an ID for the set referenced below.  Since this set is expressed as more than just an ID and a label, does that mean its ID should NOT appear above the line "type":"Set" ?

{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "http://example.org/object/123",
  "type": "HumanMadeObject",
  "_label": "Name of the Art Object",
  "member_of": [
    {
      "id": "http://id.example.com/<insert uuid here>",
      "type": "Set",
      "_label": "IAD Collection",
      "name": {
        "type": "Name",
        "_label": "My Topical Collection"
      },
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/page/aat/300378926",
          "type": "Type",
          "_label": "topical collections"
        }
      ]
    }
  ]
}

**Comment by azaroth42** [comment]
Solve API issues in the API layer, not at the intersection of model and API.

If you provide an id, and there is more data available following linked art at the URI in id, and it's not a reference (id, type, label, equivalent, plus classified_as for metatypes), then you MUST add `_fullTransclusion: False` meaning it's not fully transcluded.


```
...
{
 "id": "uri-for-birth",
 "type": "Birth",
  ...
  "_fullTransclusion": False
}
...
```

**Comment by azaroth42** [comment]
`_fullTransclusion` is hard to remember and understand which makes it less usable.  Can we instead make it `_complete` ?

e.g. if I had to explain it I would say:  You need to add this property when the record doesn't have the complete data, but you can get everything by following the link in id

**Comment by azaroth42** [comment]
Done
