### ISSUE TITLE
AAT 'commissions' in 'commissions for artwork' pattern

### ISSUE THREAD

**Issue by rpiening** [linked-art/linked.art#522]
Hi all,

I was hoping for some background information on the [commissions for artwork pattern](https://linked.art/model/provenance/promises/#commissions-for-artwork).

As I'd expected, issue #216 mentions that "Commission is another sort of Provenance Activity (per https://github.com/linked-art/linked.art/issues/275) where the classification of the main activity is commissioning (suggest - [aat:300400904](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300400904))". However in the worked-out pattern, the main activity is [300055863](http://vocab.getty.edu/aat/300055863) (Provenance activity) or, depending on what you read as main activity, [300435599](http://vocab.getty.edu/aat/300435599) ('Promise'). Does anyone remember why?

I want to model the absolute most basic information about artworks being commissioned, namely the commissioner URI and a related remark. For now, I've settled on

```	
crm:p16i_was_used_for [ 
	a crm:E7_Activity ;
	rdfs:label "Commission of Artwork" ;
	crm:P2_has_type aat:300055863 ; # provenance (history of ownership) 
	crm:P9_consists_of [ 
		a crm:E7_Activity ;
		rdfs:label "Obligation to Pay Artist" ;
		crm:P14_carried_out_by collectors:123 ; # URI to commissioner
		crm:P2_has_type aat:300435599 ; # promised gifts (legal property) 
		crm:P67i_is_referred_to_by [
			a crm:E33_Linguistic_Object ;
			crm:P2_has_type aat:300435416 ; # Descriptive note
			crm:P190_has_symbolic_content "Remark" ;
		] ;	
	] ;
] ;
```
And my instincts say that `crm:P2_has_type aat:300055863 ; # provenance (history of ownership) ` should be `crm:P2_has_type aat:300400904 ; # commissions (orders for works)` instead, in this case at least. After all, not all commissions lead to ownership by the commissioner themselves.  What are your thoughts?

Thanks!

**Comment by azaroth42** [comment]
Put this before current commission.

```
{
 "type": "Activity",
 "classified_as": [{"id": "aat:provenance_activity"}],
 "part": [{
    "classified_as": [{"id": "aat:commissioning"}],
    "carried_out_by": [{"id": "ulan:commissioning_person"}],
    "participant": [{"id": "ulan:artist"}],    //. <-- optional
   "used_specific_object": [{"id": "uri-to-the-object-that-was-commissioned"}]
  }]
}
```

**Comment by julsraemy** [comment]
We need to add `participant` to the API Event Endpoint: https://linked.art/api/1.0/endpoint/event/

**Comment by azaroth42** [comment]
Re adding `participant` ... it's beneficial for burials and baptisms as well ... the child or corpse doesn't `carry out` the activity ... and `used specific object` for them seems equally cringeworthy.

**Comment by azaroth42** [comment]
To the original question:

Commissions fall under the provenance section of the model because they're transactional -- commissioner promises to pay (and maybe pays a down payment / retainer) and the artist promises to produce the object. As such, we need a wrapper activity around the two promises (and potentially other activities like Payments), and we already have that structure with the Provenance Activity pattern.

Assuming that the commission resulted in the Production of an object, the commission activity could be the object of `caused_by` on the `Production`. (@azaroth42 to add to docs)

For classifications, I think the main activity is the aat:commissioning and the individual parts are Promises, or Payments or other aspects of the agreement.

This is somewhat related to #473 -- we would benefit from a very generic transfer class. The commissioner "transferred" their promise to the artist, who "transferred" theirs back. 

The addition of `participant` is still needed for 1.0 however, and would mirror `participated_in` on the Person record (for embedded non-identified activities like their own burial/baptism). (@azaroth42 to add to docs)
