### ISSUE TITLE
Add relative times to provenance API

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#579]
Provenance allows for `starts_after_the_end_of` and `ends_before_the_start_of` to temporally align provenance entries when dates are not known but order is. These are not in the API docs and should be.

**Comment by azaroth42** [comment]
Also on the Acquisitions in transferred_title_through on HMOs per #564

**Comment by azaroth42** [comment]
Propose to remap these names to something less terrible: `after` and `before`

**Comment by azaroth42** [comment]
Agreement on call 2024-05-29 to rename to sensible names.

**Comment by bluebinary** [comment]
After thinking about this some more, I wondered, could we potentially keep these two existing property names as they are?

- `starts_after_the_end_of`
- `ends_before_the_start_of` 

I ask, as I suspect we are one of the few institutions to currently make use of these existing property names (in our provenance metadata mapping), and the existing mapping has been in production for a number of years now, so the proposed naming change would be a breaking change for us and would require rewriting code in quite a few systems to handle the update (if we can reduce the number of breaking changes as part of the 1.0 migration that would be helpful both internally and externally for our third-party data consumers).

Secondly, although the existing names are to some extent verbose, they are descriptive, and naming clarity (some may say verbosity) is a consistent presence in Linked.Art property names, and we are not proposing to change most or really any other existing property names already in use such as `begin_of_the_begin` or `starts_before_or_with_the_start_of` for example (I think largely because they have been adopted by so many others); furthermore, there are very few single-word property names in Linked.Art, and there is something to be said for the more descriptive names we generally use throughout the model as being self-documenting to an extent whereas shorter names inherently lack much of the clarity a longer name carries.

Finally, the longer property names are akin to meaningful and descriptive names in source code; we want code (and documents) to be readable and meaningful over the long term, without too much need to refer to additional documentation for clarification; short names often lack as much meaning, whereas often slightly longer names can carry more meaning and help make documents (source code, JSON, etc) clearer to the reader, whether that reader is the original developer in the future or anyone else.

As many of us have found, the same applies to source code where although it can be a little more work to input or make use of more descriptive names when writing or creating the documents initially, this effort is far outweighed by the benefits of having more readable documents, with more descriptive names, that will be read far more times than they will ever be written.

Thank you for considering this proposal to keep the property names as they are.

**Comment by beaudet** [comment]
Seems like there should be a way to nod our heads in acknowledgement of the considerable work that's gone into the existing implementations and to embrace a developer-friendly mindset, to provide a transition period for deprecated property names like the ones in this issue so they are included in the 1.0 spec but marked as deprecated so that new implementations avoid them in favor of the newer property names but so that data consumers can still make sense of the properties and other libraries like cromulent can handle them until nobody's using those properties anymore?

**Comment by azaroth42** [comment]
I agree with Dave. There are challenges and benefits for early adopters of any in-flux system. The advantages are that all of our use cases are considered and dealt with, and we can (all) influence the direction with real, practical experience of implementing and using the specification. The challenge is that as the specification changes based on the input of the entire community, then implementations need to be updated. This applies to all of us -- no one has an implementation that will be 1.0 compliant as it stands. 

We should do our best to produce the best specification for everyone to adopt, and that means making some hard choices at times. This is where the design principles are so important, as they give us our "north star" or "guiding light" to make objective decisions rather than it potentially being a conflict. The relevant [principles](https://linked.art/api/1.0/principles/) are, I think: 

* Scope design through shared use cases: We have shared use cases for `after`, `during` and `before` but I don't think we have any use cases for more specific `starts_after_the_start_of` or `ends_before_the_end_of` (etc). Thus we should be ...
* As simple as possible, but not simpler. Which says `after` and `before`. Conversely this doesn't apply to `begin_of_the_begin` as we do have use cases for `end_of_the_begin` so can't use `start` and `end` in that situation.
* Solve at the right layer would, as Dave says, be solving in the implementation as it's an implementation problem. That doesn't mean that it's all on Getty to update everything, we can as a community work towards consistency and build products (such as crom, linkedart.js, and Digirati are building a dot net implementation, as of yet unnamed) that follow postel's law of being strict in what they send, and accepting of what they receive. At Oxford there's work on a [javascript layer](https://github.com/taiwanken/taiwanken) to process the different patterns, and here at Yale we're going to write transformers into LUX for current patterns to update to 1.0 which could be exported out into crom instead.

Any decision that we make now, we're going to have to live with for several more years. And going from 1.0 (or 1.x) to 2.0 with breaking changes will be a MUCH bigger cost for the community than from current 0.9 to 1.0 as the community will (hopefully!) be MUCH larger.

So to me it comes down to which name is easier to understand: `starts_after_the_end_of` or `after`. On the last call there was general agreement that `after` was easier to understand, but we can definitely do another poll on the next call.

I think we should assess the names of other properties as well. We already make a bunch of changes from the ontology into the JSON-LD for usability and necessity, so if there are property names that aren't clear, we should fix them now rather than later.

**Comment by azaroth42** [comment]
In documenting ... we should probably allow anywhere there's also `during` ... which is on every event or activity.  For example, the Production of something occurred `before` some event seems like a useful feature, rather than only for making provenance chains.

**Comment by azaroth42** [comment]
The linked list approach of `before`/`after` doesn't work in the simple historical ownership without `id` entries for each of the `Acquisition`s, as there's otherwise nothing to point to. However, we don't require those `id`s to be present, and typically if there's a URI, it's a separate record ... which we already recommend via the full provenance pattern.

Instead, we already have the ordering in the JSON syntax layer for the simple version, as the list of Acquisitions can be ordered correctly, and thus a naïve renderer would do the right thing by just stepping through the list. A content publisher could use the before/after links to ensure the list is correctly ordered in the JSON.
