### ISSUE TITLE
How to appropriately tag AI generated data / content

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#648]
A number of museums are working on image description projects with AI.  The NGA has a human editing workflow in place before releasing the content.  The final content is "human approved" but not necessarily "human authored" - we're not measuring how many edits editors make to these descriptions.  Should we?

But I can imagine another institution taking a different approach and releasing the descriptions without human review if a reasonable subset showed great promise or something along those lines.  In that case, the assistive text is completely AI generated, so how should we indicate this in the data so consumers can handle those data elements responsibly, such as striking from data sets used to train further AI models, any AI generated data from existing data sets (and to do it relatively easily?)

**Comment by azaroth42** [comment]
I think we should divide the discussion into a few use cases:

1. Human readable text (likely a statement, but maybe a translation of a name?) was generated by Gen AI. Example: https://lux.collections.yale.edu/view/place/52799377-bbaf-4c3a-9a5d-dd57d8694cce 
2. A value was computed somehow (ai or otherwise) such as dimensions from an image or extracted from text
3. Relationships between entities were inferred from somewhere, including textual extraction or inferencing from the graph. 

And I think for scope/sanity purposes:

1. Yes, common and like relatively easy to deal with.  (cf #635)
2. Less common, still relatively easy to deal with. (would go in the attribute assignment for how it was measured)
3. Don't know how common, but very complicated to deal with. Propose out of scope. (would need reification of the relationship)

**Comment by azaroth42** [comment]
Noting up front that AI (in CRM) is not a human and thus it's not who carried out the activity. It would be a tool that a person used, and thus would live in `used_specific_object` to reference the AI itself or `technique` if it's just "generated by AI". AAT terms -- https://vocab.getty.edu/aat/300251574 and https://vocab.getty.edu/aat/300456647 are useful, but neither are techniques per se.

**Comment by azaroth42** [comment]
Proposal to discuss:

Option 1 -- be specific about tool:

* 1 is in scope. add `used_specific_object` to an AI in the `Creation` of the text.
* 2 is in scope. add `used_specific_object` to an AI in the `AttributeAssignment` of the `Dimension`.
* 3 is out of scope

Would probably want the AI to be a `DigitalService`, classified_as an AI somehow?
But we would need some way to identify AIs!

Option 2 -- be general:

Alternative would be to add a `technique` of "AI generated" to the Creation / AttributeAssignment.

Could do both?

**Comment by azaroth42** [comment]
Yes do both :)

**Comment by azaroth42** [comment]
Ask Patricia for a technique in AAT for AI Generated

**Comment by beaudet** [comment]
Thinking about sustaining vocabulary terms in general, can we mint AAT candidate concepts initially on the linked.art domain so that they are immediately available as concepts? That way, if Getty declines a request for a specific term for whatever reason then we still have a community recognized term to use.  Once Getty has added to the AAT, we can set a deprecation schedule for the term if anyone in the community is actively using the linked art hosted term.  That would eliminate any road blocks for organizations doing active development and hopefully the GRI will continue to respond quickly enough so deprecation isn't even needed.  But having a resolvable endpoint for a concept before it's actually published to AAT seems like it would be helpful?

**Comment by kkdavis14** [comment]
will ask for IDs for both AI as technique and as a descriptive classification

**Comment by kkdavis14** [comment]
A good thing to note re: AAT: we should always come prepared with sources. 

The LUX record Rob notes above is one source for "AI content" (as a parent to AI art classification). 
We've also provided https://www.moma.org/calendar/exhibitions/5535 as a source for "AI generated" (technique). 

Are there any further sources available to provide fodder for our argument?

**Comment by beaudet** [comment]
Yes, we're using an AI process to write alt tags for images.  They're edited by people before entering into our systems, but I imagine we would want to tag that content with something like a "partially AI generated" classification to prevent it from being used as training data for an LLM.

**Comment by azaroth42** [comment]
Technique's aat: 300456842 ("AI Generation")

Content classification's aat: 300456841 ("AI Generated Content")

**Comment by azaroth42** [comment]
Done

**Comment by beaudet** [comment]
What about content that was initially generated by AI then reviewed and edited by a human?  Is that human generated content, AI generated content, or something in between?

**Comment by kkdavis14** [comment]
@beaudet it's interesting, because we don't feel the need to classify when a human has edited things, generally. could it be two classifications, and the human-made one is 300224592 ("man-made"-AAT should really update that label)? the process of editing isn't clear in this modeling, but the fact that it was both AI and human engineered is.

**Comment by azaroth42** [comment]
I think the model and API capabilities are there -- we can always ask for more vocabulary terms, or invent them as needed.

From the CRM's ontological perspective, everything is made by human, even if the only involvement was to click the button that got the AI to do all the work. This is why it's `used_specific_object` for the AI, rather than `carried_out_by` the AI. We need to reconsider software's agency for future versions (also animals, spiritual entities, and so on) but not for 1.0

**Comment by beaudet** [comment]
If there's a technique available, the following seems like a reasonably nuanced way of expressing that image descriptions involved assistance from AI.  Yes?

```
  "type": "LinguisticObject",
  "label": "Description of the image",
  "created_by": {
    "type": "Activity",
    "label": "Authoring of image descriptions with AI assistance",
    "technique": {
      "type": "Concept",
      "id": "http://vocab.getty.edu/aat/300456842",
      "label": "AI Generation"
    }
  }
}
```

**Comment by aisaac** [comment]
Hmm actually @beaudet I have a question about this solution. It works well with descriptions, which was your starting point but I have doubts it would be generalizable, which the ticket title suggests. I.e. if we would apply the pattern to say, an AAT subject assignment, this would hint that the AAT concept has been created by an AI process (as opposed to the "tagging" of the object with the AAT concept), wouldn't it?

**Comment by azaroth42** [comment]
Call of 11/27, ensure documentation is clear about the scope -- e.g. we're not going to reify relationships, only add additional properties within the model

**Comment by azaroth42** [comment]
Done
