### ISSUE TITLE
exhibition-specific-labels should also be made out as Title

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#85]
http://linked.art/model/exhibition/#exhibition-specific-labels:
I think that both "Exhibition Specific Name" and "Real Painting Name" should be also made out as Title.
There is no AAT concept for "exhibition label", should we ask Patricia to make one?

**Comment by workergnome** [comment]
What's the benefit of using Title instead of Appellation?  It's slightly more specific, but, as you say, it's not fully specific enough to capture "exhibition label", and so it just adds complexity to the model (requiring either UNION or inferencing to query all possible appellations) without minimal semantic benefit.

**Comment by azaroth42** [comment]
Agreed. This is counter to the design principles. Closing.

**Comment by VladimirAlexiev** [comment]
I should have been more specific what I mean by "made out as".
I don't mean to criticize here the throwing away of some classes (that's a separate topic). 
So in this issue, `s/Title/Appellation/` as you see fit.

I mean that you should make links from the object to these two titles, as per http://linked.art/model/object/identity/#titles. 
Else one can't find the exhibition label amongst the other titles of an object.

And make AAT concept "exhibition label" to use as that title's type.

**Comment by azaroth42** [comment]
That's the same as #86, I think.  If the museum publisher of the description considers that the title is a real title, then they can do that.  The additional feature that the AttributeAssignment pattern allows is for the publisher to have an Appellation that exists, but is intentionally not declared as an Appellation of the object directly.  The difference between:

> "A title of this is X"   (MMO identified_by Appellation)

and 

> "Someone else said that a title of this is X" (AttrAssn assigned Appellation, assigned_to MMO)

**Comment by VladimirAlexiev** [comment]
Using this approach means that you'll never integrate data from several places.
If you find an artist title in a catalog raisonne and a repository title in a museum catalog, won't you make both of them as titles?

@mdlincoln What do you think? Is an exhibition label a title or not?

**Comment by workergnome** [comment]
I think the issue then is that it means that to integrate data, we're going to have to convince everyone to use the AttributionAssignment pattern in all cases, because for more complex cases we're going to have to use it—and if we want "One Pattern To Rule Them All", it has to be the most complicated pattern.

As I understand it, the design methodology we're going with is to allow the simplest pattern that will work, allowing more complex patterns to exist, and having a out-of-band way to reduce complex patterns into simpler ones.  This fits well with the CIDOC-CRM 'shortcut' pattern—the rules that allow Long-Cuts to be expanded to short-cuts don't exist, but are easily computable.

So, I think what we're saying is that in the data-mapping layer, you shouldn't need to record both paths.  In an application layer, you may choose to expand the patterns or condense them—but as long as that is possible without creating paradoxes, you don't have to instantiate all of those triples.

This also means that some of these patterns cannot be simplified using a specific technique, such as OWL inferencing.  I'd be up for a discussion as to what the rules and limitations are there—but that's probably best done in a separate issue.

**Comment by azaroth42** [comment]
I agree. Always using AttributeAssignment defeats the basic principle of making something that's practical and scales well for complexity.  We already have the two patterns -- use `Appellation` if you believe that the value is a Title of the object, use `AttributeAssignment` if either you're recording someone else's belief that you do not agree with, or if the statement is true only within a particular contextual frame of reference.

We're not concerned with how the data is managed, we're concerned with how it is presented to external systems. If every triple is reified internally and then most are simplified on the way out, then that's cool, but not the concern of an interoperability layer. 

If /that/ is the issue, then I propose close wontfix.

**Comment by VladimirAlexiev** [comment]
@workergnome shortcut->longpath rules exist in the form of FOL existential statements in the CRM spec.

@azaroth42 "Always using AttributeAssignment defeats the basic principle of making something that's practical": I completely agree so I don't see those existential rules as useful. The purpose of a longpath is to record extra info, so there's no point making it if you don't have that extra info.

(I was told "the longpath is then a placeholder to put the extra info when it comes about"... But if you push this reasoning, maybe we should also reify AttributeAssignments as 3 more AttributeAssignments... ad nauseum ;-))

@workergnome "You shouldn't need to record both paths": this argument is flawed. It's in fact useful to to record shortcut when you have a longpath, to aid querying, and to store the fact you believe 

@azaroth42  "use Appellation if you believe that the value is a Title of the object": we've come to the crux of this issue. Do you guys (incl @mdlincoln) believe that is so or not?

Please don't tell me it's the best to be mum about this issue: remember what happened when you left AAC URL's unspecified.

**Comment by azaroth42** [comment]
> "use Appellation if you believe that the value is a Title of the object": we've come to the crux of this issue. Do you guys (incl @mdlincoln) believe that is so or not? 

That's not up to us to decide. We have provided the two ways to model the information, the simple way if you believe it is the title, and the longer way if you don't. By asserting that, e.g., all labels regardless of who created them in what context must be asserted as Appellations of the object will result in the organizations that do NOT think they are titles leaving out the data completely.

**Comment by VladimirAlexiev** [comment]
So please describe these alternatives. By being mum that an exhibition label is sometimes/often a title, you leave mappers guessing (remember what happened when you left AAC URL's unspecified: half the AAC bugs are non-sensical URLs).

Title vs AttributeAssignment are not exclusive. If an exhibition label is considered a title, it should also be made out as AttributeAssignment to provide the link to the exhibition.
