### ISSUE TITLE
Better AAT term for 'description'

### ISSUE THREAD

**Issue by workergnome** [linked-art/linked.art#91]
Currently, we're using 300080091, which is "description (activity)".  Thanks to vlad, we now have  aat:300411780 "descriptions (documents)", which is probably more correct.

Should we change this out?

**Comment by azaroth42** [comment]
Sure, we're still changing things up, so we might as well fix this. It does raise a bigger question though ...

Are we going to ask for documentized versions of _all_ of the statement classifications? It's starting to sound like we _are_ managing our own set of classes if we're too concerned about the exact semantic match between CRM classes and AAT concepts :(

**Comment by workergnome** [comment]
You're the semantician—are they a good enough match?  😸.  

As the software person, I care that there's consistency, and that the documentation is clear enough that if someone wants to tag a new concept, they would gravitate to the same thing that we would pick.  If there _had been_ a "description (document)" class, we certainly would have picked it over the activity, I think.

Consistency is easy (though the linked.art use cases).  Documentation is harder.  And are we maintaining it, or is AAT managing it?

**Comment by azaroth42** [comment]
I think we need to maintain the list of concepts (aat or otherwise) that we use or recommend (as per community/best-practices/vocabularies/). Given the number of vocabularies in CH, and the number of terms in AAT (let alone others), I don't think that there's much chance of serendipitous alignment. We just need to pick them as the use cases come up, and if they don't exist, request them.
